// AUTO-GENERATED — scripts/generate-companies.mjs 로 마스터시트에서 생성.
// 손으로 고치지 말 것. 총 493건 · beauty 14 · skincare 479 · 이메일 472.
//
// ⚠️ 연락처(email 등)는 서버 데이터다. 이 파일은 서버에서만 import되며(lib/codes.ts),
//    개인화 페이지(클라이언트)로는 code/brand/segment/gubun 만 넘긴다.

export interface Company {
  code: string;
  brand: string;
  segment: "beauty" | "skincare";
  gubun: string;
  email?: string;
  contactEmail?: string;
  contactName?: string;
  instagram?: string;
  phone?: string;
}

export const COMPANIES: Company[] = [
  { code: "ABM6381", brand: "ABMT (abmt)", segment: "skincare", gubun: "", email: "", contactEmail: "abmtkorea@naver.com", contactName: "", instagram: "@abmt_official", phone: "" },
  { code: "ACC5576", brand: "K.BEAUTY ACCESSORY CO.,LTD", segment: "skincare", gubun: "", email: "sunjing@k.beautychina.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ACE2658", brand: "ACEFARM ((주)에이스팜)", segment: "skincare", gubun: "", email: "", contactEmail: "contact@acefarminc.com", contactName: "", instagram: "", phone: "" },
  { code: "ACE8992", brand: "(주)에이스피부임상연구소", segment: "skincare", gubun: "", email: "aceskin@acescri.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ACF3888", brand: "ACFIT / VMEDISPA (Blue Peel | V-sang gel | V-sang Pack)", segment: "skincare", gubun: "", email: "", contactEmail: "acfit.kr@gmail.com", contactName: "이유정", instagram: "@acfit.official", phone: "010-8385-6013" },
  { code: "ADS6672", brand: "주식회사 에이디솔루션", segment: "skincare", gubun: "더마", email: "adsolution52@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "AES2772", brand: "AESTHEIN", segment: "skincare", gubun: "더마", email: "aesthein_sa@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "AGA7684", brand: "주식회사 아가파월드", segment: "skincare", gubun: "홈디바이스", email: "info@agafar.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "AHA5923", brand: "Ahan (에이한에브리웨어(주))", segment: "skincare", gubun: "", email: "", contactEmail: "david@ahan.co.kr", contactName: "천동환", instagram: "", phone: "010-8726-4896" },
  { code: "AHC1724", brand: "A&H INTERNATIONAL COSMETICS CO., LTD", segment: "skincare", gubun: "", email: "info-sales@a-hcosmetics.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "AIP5677", brand: "아이뽀", segment: "skincare", gubun: "스킨케어", email: "aippo1@starluxe.co.kr", contactEmail: "", contactName: "", instagram: "@aippo.official", phone: "" },
  { code: "AIR2762", brand: "AIRAPHA / 주식회사 에어라파", segment: "skincare", gubun: "", email: "", contactEmail: "airaphaoffice2@airapha.com", contactName: "성은지", instagram: "", phone: "010-2280-3440" },
  { code: "ALE1818", brand: "all-eyes (올아이즈)", segment: "skincare", gubun: "", email: "", contactEmail: "yjkang@all-eyes.kr", contactName: "강영진", instagram: "", phone: "010-5368-5424" },
  { code: "ALL5146", brand: "올어바웃아이즈", segment: "beauty", gubun: "메이크업", email: "alleyes@all-eyes.kr", contactEmail: "", contactName: "", instagram: "@madamelash_official", phone: "" },
  { code: "ALW4773", brand: "올웨이즈비퓨어", segment: "skincare", gubun: "스킨케어", email: "steven@kailani-int.com", contactEmail: "", contactName: "", instagram: "@alwaysbepure_global", phone: "" },
  { code: "AML2553", brand: "AMORY LONDON LTD", segment: "skincare", gubun: "", email: "info@amorylondon.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "AND1180", brand: "C AND K / 주식회사 씨앤드케이 (COSMETIC OEM, ODM, BRAND SALES, Overseas Business)", segment: "skincare", gubun: "", email: "", contactEmail: "kschace@gmail.com / ksch204@naver.com", contactName: "강석찬", instagram: "", phone: "010-4818-8606" },
  { code: "ANO5752", brand: "ANOETIC BEAUTY", segment: "skincare", gubun: "스킨케어", email: "leokim@anoetic.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ANT4745", brand: "안탈라", segment: "skincare", gubun: "더마", email: "official@antala.one", contactEmail: "official@antala.one", contactName: "곽도원", instagram: "@antala_official", phone: "010-7367-5709" },
  { code: "ARA1695", brand: "ArAz / BEAUTYMOA (Poly Clean)", segment: "skincare", gubun: "", email: "", contactEmail: "poly2019@hanmail.net", contactName: "양선호", instagram: "", phone: "010-5112-0182" },
  { code: "ARH8483", brand: "aram HUVIS", segment: "skincare", gubun: "", email: "", contactEmail: "Stella@aramhuvis.com", contactName: "이수경", instagram: "", phone: "010-7330-3540" },
  { code: "ARN2405", brand: "ARNE", segment: "skincare", gubun: "", email: "", contactEmail: "foliecosmetics@naver.com", contactName: "홍혜원", instagram: "@folie__hong", phone: "010-9382-6237" },
  { code: "ARN3166", brand: "Aroma Newtech / (주)아로마뉴텍", segment: "skincare", gubun: "", email: "", contactEmail: "sam@aromanewtech.com", contactName: "이상훈", instagram: "", phone: "010-5206-7576" },
  { code: "ARO1176", brand: "(주)아로마뱅크", segment: "skincare", gubun: "", email: "aromabank@aroma-bank.co.kr", contactEmail: "grantlee@aroma-bank.co.kr / aromabank@aroma-bank.co.kr", contactName: "이승건", instagram: "", phone: "010-9999-1612" },
  { code: "ARO3793", brand: "어룸", segment: "skincare", gubun: "스킨케어", email: "semin@anomalylabs.biz", contactEmail: "", contactName: "", instagram: "@aroomskin", phone: "" },
  { code: "ARO6001", brand: "(주)에이로마플라붐", segment: "skincare", gubun: "", email: "info@aromaflavum.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ARO9273", brand: "아로다", segment: "beauty", gubun: "메이크업", email: "rainsy@dashopmall.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ART7517", brand: "(주)아트페이스", segment: "beauty", gubun: "메이크업/스킨케어", email: "", contactEmail: "artface@artfacekorea.com", contactName: "라경식", instagram: "@tenzero_official", phone: "010-5176-1140 / 010-6283-2942" },
  { code: "ASI6517", brand: "ASIABNC (주식회사 아시아비엔씨)", segment: "skincare", gubun: "", email: "export@asiabnc.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BAI5410", brand: "BaiChang / 深圳市百昌科技有限公司 (SHENZHEN BAICHANG TECHNOLOGY CO., LTD)", segment: "skincare", gubun: "", email: "", contactEmail: "ella@baichangkeji.com", contactName: "金美玲", instagram: "", phone: "+86 137 9529 9545" },
  { code: "BAI9715", brand: "BAIHUA CO.,LTD", segment: "skincare", gubun: "", email: "joan@baihuawipes.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BAT1764", brand: "(주)배쓰프로젝트", segment: "skincare", gubun: "바디", email: "office@bathproject.kr", contactEmail: "mint@bathproject.kr", contactName: "이다경", instagram: "@bathproject", phone: "010-4493-4544" },
  { code: "BCC9612", brand: "BOTA C X Choi's Choice lab", segment: "skincare", gubun: "스킨케어", email: "cheonghaedam@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BCM4029", brand: "BELLE CRAFT MANUFACTURING CO.,LTD.", segment: "skincare", gubun: "", email: "marketing@belleglas.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BEA5997", brand: "뷰핸", segment: "skincare", gubun: "바디", email: "beauhan@diami.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BEA9120", brand: "(주)뷰티앤팩토리", segment: "skincare", gubun: "더마", email: "global@beautynfactory.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BEL3977", brand: "벨플라워", segment: "skincare", gubun: "스킨케어", email: "bellflower.cs@gmail.com", contactEmail: "", contactName: "", instagram: "@bellflower_kor", phone: "" },
  { code: "BEL3980", brand: "Beaufirst Global Company Limited", segment: "skincare", gubun: "더마/스킨케어", email: "Beaufirstglobal@gmail.com", contactEmail: "eviralabglobal@gmail.com", contactName: "", instagram: "", phone: "" },
  { code: "BEL7437", brand: "디어메이", segment: "beauty", gubun: "메이크업", email: "oversea@beleco.co.kr", contactEmail: "", contactName: "", instagram: "@dearmay.official", phone: "" },
  { code: "BEN1949", brand: "(주)제이코모", segment: "skincare", gubun: "스킨케어", email: "benetus@jcomo.co.kr", contactEmail: "", contactName: "", instagram: "@benetus_official", phone: "" },
  { code: "BEN5100", brand: "(주)벤치컴퍼니 Bench company Inc", segment: "skincare", gubun: "스킨케어", email: "hglee@benchcompany.kr", contactEmail: "", contactName: "", instagram: "@fitroot", phone: "" },
  { code: "BEP2403", brand: "BE-PRESENCE (비프레즌스)", segment: "skincare", gubun: "", email: "", contactEmail: "kmw@behopebeauty.com / mw0505@naver.com", contactName: "김민우", instagram: "", phone: "010-2393-6706" },
  { code: "BES5852", brand: "주식회사 베스트솔루션", segment: "skincare", gubun: "", email: "sales@bestsolution1.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BFO7356", brand: "오오유 주식회사", segment: "skincare", gubun: "스킨케어", email: "contact.bfou@gmail.com", contactEmail: "", contactName: "", instagram: "@bfou.official", phone: "" },
  { code: "BIG7799", brand: "BIO GLORIOUS CO.,LTD.", segment: "skincare", gubun: "더마", email: "bioglorious@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BIJ6394", brand: "BIJU (bijugroup)", segment: "skincare", gubun: "", email: "", contactEmail: "sera@bijugroup.com", contactName: "김상은", instagram: "", phone: "010-5358-8943" },
  { code: "BIO2642", brand: "BIOSPECTRUM", segment: "skincare", gubun: "", email: "", contactEmail: "biogu@biospectrum.com", contactName: "유소희", instagram: "", phone: "010-5779-0118" },
  { code: "BIO8797", brand: "BiOBiO Co.,Ltd.", segment: "skincare", gubun: "바디", email: "biobiocos@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BIO8813", brand: "㈜바이오에프디엔씨", segment: "skincare", gubun: "더마", email: "global@biofdnc.com", contactEmail: "dishin@biofdnc.com", contactName: "신동일", instagram: "", phone: "010-2817-8603" },
  { code: "BKX9065", brand: "비컨", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BLA3556", brand: "blancdoux (블랑두)", segment: "skincare", gubun: "", email: "", contactEmail: "kihyun819@blancdoux.com", contactName: "한기현", instagram: "", phone: "010-3039-8190" },
  { code: "BLU8729", brand: "바이오셀힐 & 카토-카토", segment: "skincare", gubun: "더마", email: "sallyshen__@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BNC9767", brand: "성림 BNC", segment: "skincare", gubun: "홈디바이스", email: "sunglimbnc@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BOD3159", brand: "Bodycare Lab", segment: "skincare", gubun: "홈디바이스", email: "contact@bcl.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BOH3345", brand: "BODYYA HEALTH", segment: "skincare", gubun: "", email: "bodyya@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BON6795", brand: "BonitoLab", segment: "skincare", gubun: "", email: "bonitolab@bonitolab.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BOT5446", brand: "BOTA C (K-GLOW)", segment: "skincare", gubun: "", email: "", contactEmail: "kglowmelb@gmail.com", contactName: "DOYEON KIM", instagram: "@botac_official", phone: "+61 415 827 009" },
  { code: "BOT7937", brand: "주식회사 보타닉센스", segment: "skincare", gubun: "스킨케어", email: "info@botanicsens.com", contactEmail: "tspark@yonsei.ac.kr", contactName: "박태선", instagram: "@botanicsens", phone: "010-8972-3123" },
  { code: "BPF2661", brand: "라즐라 뷰티(P.M.U)", segment: "skincare", gubun: "", email: "bpflkhss@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BRB6836", brand: "(주)바라보니화장품", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BRI4437", brand: "비오아이", segment: "skincare", gubun: "바디", email: "jaypal_company@naver.com", contactEmail: "jaypal_company@naver.com", contactName: "이정서", instagram: "@bringorganic_official", phone: "010-6279-6396" },
  { code: "BRT7105", brand: "브라이트", segment: "skincare", gubun: "더마", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BTF6509", brand: "BTF", segment: "skincare", gubun: "홈디바이스", email: "hanmaum117@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "BTY5760", brand: "비티랩", segment: "skincare", gubun: "", email: "", contactEmail: "btylab8082@naver.com", contactName: "김원석", instagram: "", phone: "010-2264-8686" },
  { code: "BUB9261", brand: "주식회사 해피웍스컴퍼니", segment: "skincare", gubun: "바디", email: "jjh@slowness.co.kr", contactEmail: "", contactName: "", instagram: "@bubblemonkey_official", phone: "" },
  { code: "BUE4676", brand: "브에노메디텍", segment: "skincare", gubun: "더마", email: "ds2oph@naver.com", contactEmail: "", contactName: "", instagram: "@bueno.official", phone: "" },
  { code: "BUL9697", brand: "Bullsone Co., Ltd. (Love My Car)", segment: "skincare", gubun: "", email: "", contactEmail: "minjeong.park@bullsone.com", contactName: "박민정", instagram: "", phone: "010-8999-7707" },
  { code: "BYD1737", brand: "드림인사이트 (bydream)", segment: "skincare", gubun: "", email: "", contactEmail: "nmj0309@bydream.co.kr", contactName: "노민정", instagram: "", phone: "010-8061-0039" },
  { code: "BYT8329", brand: "바이더퀄리티", segment: "skincare", gubun: "더마", email: "bythequality@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CAF2297", brand: "(주)카푸네인터내셔널", segment: "skincare", gubun: "헤어", email: "t2o3p@naver.com", contactEmail: "", contactName: "", instagram: "@teamcafune.official", phone: "" },
  { code: "CAM2796", brand: "주식회사 드림코스", segment: "skincare", gubun: "스킨케어", email: "cp@dreamcos.co.kr", contactEmail: "cp@dreamcos.co.kr", contactName: "MIN HO", instagram: "", phone: "010-8949-8427" },
  { code: "CAR5812", brand: "Caregen Co., Ltd.", segment: "skincare", gubun: "", email: "sales@caregen.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CEL1876", brand: "유앤미코스매틱", segment: "skincare", gubun: "스킨케어", email: "cellio2023@naver.com", contactEmail: "cellio2023@naver.com", contactName: "김현아", instagram: "@celliocosmetic_official", phone: "010-4661-1802" },
  { code: "CEL2193", brand: "(주) 에이바이오머티리얼즈", segment: "skincare", gubun: "", email: "master@a-bio.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CEL3020", brand: "셀릭사", segment: "skincare", gubun: "더마", email: "kns.cosmetic@gmail.com", contactEmail: "", contactName: "", instagram: "@celixa_official", phone: "" },
  { code: "CEL6186", brand: "CELLECO ((주)셀레코)", segment: "skincare", gubun: "", email: "", contactEmail: "acelsh89@celleco.co.kr", contactName: "이승환", instagram: "", phone: "010-2577-9049" },
  { code: "CEL6437", brand: "CELLEA/BELLADIA", segment: "skincare", gubun: "스킨케어", email: "fcsecond@fcsecond.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CEL7588", brand: "셀비오코스메틱(주)", segment: "skincare", gubun: "스킨케어", email: "cellviocosmetic@naver.com", contactEmail: "", contactName: "", instagram: "@cellvio_offlcial", phone: "" },
  { code: "CEL8625", brand: "㈜세레코", segment: "skincare", gubun: "", email: "celleco@celleco.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CEL8757", brand: "주식회사 셀락바이오", segment: "skincare", gubun: "", email: "cellarkbio@cellarkbio.com", contactEmail: "blackb4@cellarkbio.com", contactName: "노용배", instagram: "", phone: "010-3065-9776" },
  { code: "CEL8769", brand: "주식회사 라콤 (CELL29)", segment: "skincare", gubun: "더마", email: "", contactEmail: "lacom_official@naver.com", contactName: "김종혁", instagram: "@cell29.official", phone: "010-3205-3794" },
  { code: "CEL9409", brand: "celebon", segment: "skincare", gubun: "스킨케어/더마", email: "dhoh@hlmc.co.kr", contactEmail: "stjung@hlmc.co.kr", contactName: "정선택", instagram: "@celebon_kr", phone: "010-9910-8029" },
  { code: "CEP5680", brand: "세포랩", segment: "skincare", gubun: "더마", email: "cepolab@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CET1169", brand: "CETERA", segment: "skincare", gubun: "더마", email: "ceterakorea@naver.com", contactEmail: "", contactName: "", instagram: "@cetera.official", phone: "" },
  { code: "CHA1269", brand: "채운", segment: "skincare", gubun: "스킨케어", email: "official@chaewun.com", contactEmail: "Nani@chaewun.com", contactName: "김란", instagram: "@chaewun.official", phone: "010-3097-4327" },
  { code: "CHA4092", brand: "차모스코스메틱", segment: "skincare", gubun: "", email: "", contactEmail: "1992@chamos.co.kr", contactName: "윤동제", instagram: "", phone: "010-2380-1088" },
  { code: "CHA6201", brand: "주식회사 제이비무역", segment: "skincare", gubun: "홈디바이스", email: "yrkwoon@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CHB1340", brand: "주식회사 씨에이치바이오", segment: "skincare", gubun: "스킨케어", email: "chbiokorea@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CHE3725", brand: "웰본", segment: "skincare", gubun: "헤어", email: "export@welcomesgroup.com", contactEmail: "", contactName: "", instagram: "@cheongdamstyleshop_official", phone: "" },
  { code: "CHO7301", brand: "㈜프롬비건", segment: "skincare", gubun: "스킨케어", email: "cdysr@fromvegan.co.kr", contactEmail: "", contactName: "", instagram: "@chorokchorong.official", phone: "" },
  { code: "CIC6889", brand: "(주)시카젠", segment: "skincare", gubun: "더마", email: "cicagen@cicagen.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CIT7674", brand: "주식회사 씨아이티 (CIT Co., Ltd)", segment: "skincare", gubun: "", email: "andrew@citcosmetic.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CKN2661", brand: "(주) 씨케이앤비", segment: "skincare", gubun: "", email: "sales@cknb.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CLA5344", brand: "CLAIRLISSE", segment: "skincare", gubun: "더마", email: "", contactEmail: "9438250gw@gmail.com", contactName: "정겨운", instagram: "", phone: "010-8695-9006" },
  { code: "CLA5648", brand: "에브리데이 클랩스", segment: "skincare", gubun: "더마", email: "claps01@naver.com", contactEmail: "", contactName: "", instagram: "@claps__official", phone: "" },
  { code: "CMD8736", brand: "에이치알메디텍", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CME8644", brand: "(주)씨메드 / CMED COSMETICS", segment: "skincare", gubun: "", email: "", contactEmail: "cmedemi@naver.com", contactName: "하니", instagram: "", phone: "010-9806-6466" },
  { code: "CNC2855", brand: "주식회사 씨앤씨플래닛", segment: "skincare", gubun: "스킨케어", email: "hu1998@cncplanet.co.kr", contactEmail: "", contactName: "", instagram: "@cnc_planet", phone: "" },
  { code: "CNT6328", brand: "씨앤텍(주)", segment: "skincare", gubun: "", email: "sbeom1@cntechcorp.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "COC6864", brand: "COCAP / CUBECAP CO., LTD.", segment: "skincare", gubun: "", email: "", contactEmail: "lypark@cubecap.co.kr", contactName: "Leeyoung Park", instagram: "", phone: "010-9897-2090" },
  { code: "COR1221", brand: "CORE INTERNATIONAL / 주식회사 코어인터내셔널", segment: "skincare", gubun: "", email: "", contactEmail: "hjlee@corehb.co.kr / coreintl@corehb.co.kr", contactName: "이효진", instagram: "", phone: "010-7159-9424" },
  { code: "COS2757", brand: "(주) 코스모더마", segment: "skincare", gubun: "", email: "comikorea@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "COS4417", brand: "(주)코스모어플러스", segment: "skincare", gubun: "스킨케어", email: "cosmoreplus@cosmoreplus.com", contactEmail: "mj.kim@cosmoreplus.com / cosmoreplus@cosmoreplus.com", contactName: "김민지", instagram: "@revcell_official", phone: "010-3053-9330" },
  { code: "COS5629", brand: "㈜나인원코스메디", segment: "skincare", gubun: "더마", email: "official@91cosmedi.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CPX1993", brand: "C&C PLANET (brands: filflo, 3W8L)", segment: "skincare", gubun: "", email: "", contactEmail: "kevin@cncplanet.co.kr", contactName: "한규연", instagram: "", phone: "010-2866-5580" },
  { code: "CRE3638", brand: "SM 삼환기업 (SM그룹) / cremorlab", segment: "skincare", gubun: "", email: "", contactEmail: "KHS@Samwhan.co.kr", contactName: "김현수", instagram: "", phone: "010-4024-3992" },
  { code: "CUE7453", brand: "(주)씨유스킨", segment: "skincare", gubun: "더마", email: "info@cuskin.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "CUR7231", brand: "CuraPulse", segment: "skincare", gubun: "", email: "", contactEmail: "ysyang@cura-pulse.com", contactName: "양용승", instagram: "", phone: "010-8929-1154" },
  { code: "CUS8388", brand: "CU (주)CU스킨 / CUSKIN", segment: "skincare", gubun: "", email: "", contactEmail: "kkyh0024@cuskin.co.kr", contactName: "강연형", instagram: "", phone: "010-7111-6595" },
  { code: "DAS6145", brand: "주식회사 다산씨엔텍", segment: "skincare", gubun: "", email: "sales@dasancntech.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DAV7708", brand: "다빈홀딩스", segment: "skincare", gubun: "바디", email: "vector@davinnature.com", contactEmail: "vector@davinnature.com", contactName: "백승호", instagram: "@davinnature_kiddums", phone: "+82. 10. 7560. 2737" },
  { code: "DAW8709", brand: "DAILY WEEKLY", segment: "skincare", gubun: "스킨케어", email: "trading@dailyweekly.co.kr", contactEmail: "", contactName: "", instagram: "@dailyweekly.official", phone: "" },
  { code: "DAY1770", brand: "㈜3일애", segment: "skincare", gubun: "더마", email: "sales@3dayslove.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DAY8037", brand: "데이셀코스메틱 주식회사", segment: "skincare", gubun: "더마", email: "lancert@daycell.com", contactEmail: "", contactName: "", instagram: "@daycell.official", phone: "" },
  { code: "DEH3113", brand: "DESIGN HANA", segment: "skincare", gubun: "", email: "", contactEmail: "anna980802@gmail.com", contactName: "성안나", instagram: "", phone: "010-4524-3608" },
  { code: "DEL9814", brand: "딜라이트 (Delight)", segment: "skincare", gubun: "", email: "", contactEmail: "ceo@delight.kr", contactName: "정규환", instagram: "@ht.kr", phone: "010-3926-5651" },
  { code: "DEM3439", brand: "DEAR.MAY (dearmay) / Beleco", segment: "skincare", gubun: "", email: "", contactEmail: "lihui0705@beleco.co.kr", contactName: "이혜", instagram: "", phone: "010-5820-7521" },
  { code: "DER1380", brand: "dermalab (주)더마랩", segment: "skincare", gubun: "", email: "", contactEmail: "sales04@dermalab.co.kr", contactName: "한나", instagram: "", phone: "010-7121-6790" },
  { code: "DER2796", brand: "주식회사 더마라인", segment: "skincare", gubun: "더마", email: "leejy@dermaline.co.kr", contactEmail: "", contactName: "", instagram: "@dermaline_korea", phone: "" },
  { code: "DER3189", brand: "(주)씨케이리제온", segment: "skincare", gubun: "헤어", email: "dermaregeon@ckregeon.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DER3356", brand: "주식회사 더마솔루션", segment: "skincare", gubun: "", email: "hello@derma-solution.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DER4625", brand: "DERMALINE (DESIGN YOUR BEAUTY)", segment: "skincare", gubun: "", email: "", contactEmail: "jeonjs@dermaline.co.kr", contactName: "전지선", instagram: "", phone: "010-9913-3442" },
  { code: "DER9753", brand: "더마밀", segment: "skincare", gubun: "", email: "sales@dermameal.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DES8573", brand: "디자인바른", segment: "skincare", gubun: "", email: "db@designbarun.com", contactEmail: "master@designbarun.com", contactName: "최지연", instagram: "@nbarun.com", phone: "010-3546-0608" },
  { code: "DEW2365", brand: "쥬네뷰", segment: "skincare", gubun: "스킨케어", email: "dewdap@naver.com", contactEmail: "", contactName: "", instagram: "@dewdap.official", phone: "" },
  { code: "DEW3421", brand: "DEWVERO", segment: "skincare", gubun: "스킨케어", email: "nscompany123@naver.com", contactEmail: "nklee@dewvero.com", contactName: "이남기", instagram: "@dewvero_official", phone: "010-7139-2569" },
  { code: "DEY9773", brand: "DERMA YOURCELL", segment: "skincare", gubun: "더마", email: "fruitsjuice@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DIA4614", brand: "DIAMI · beauhan · FANTASYNAILS", segment: "skincare", gubun: "", email: "", contactEmail: "pmh@diami.co.kr", contactName: "박명희", instagram: "", phone: "010-6405-8425" },
  { code: "DKT4489", brand: "DONGGUAN KINWONG TECHNOLOGY CO.,LTD", segment: "skincare", gubun: "", email: "miko@jingwangtop.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DOB1089", brand: "(주)동방 B&H (Dongbang B&H Co., Ltd.)", segment: "skincare", gubun: "", email: "", contactEmail: "james@dongbangbnh.com", contactName: "James Hwang", instagram: "", phone: "010-2965-8003" },
  { code: "DOC9840", brand: "DocLab Korea (닥랩코리아)", segment: "skincare", gubun: "", email: "", contactEmail: "doclabkorea@daum.net", contactName: "남광우", instagram: "", phone: "010-2757-1001" },
  { code: "DON2084", brand: "뷰가닉", segment: "skincare", gubun: "헤어", email: "james@dongbangbnh.co", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DOO9232", brand: "주식회사 두봄", segment: "skincare", gubun: "스킨케어", email: "doobom7727@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DOS6265", brand: "디오에스앤유니크", segment: "skincare", gubun: "홈디바이스", email: "help@doskorea.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DRP6513", brand: "피텐", segment: "skincare", gubun: "더마", email: "pms@pitenkorea.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DRP8560", brand: "아이프로덕트", segment: "skincare", gubun: "향수", email: "global@iproduct.co.kr", contactEmail: "", contactName: "", instagram: "@dr.percent_official", phone: "" },
  { code: "DRP8618", brand: "Dr.pepti / (주)제이앤코슈 J&COCEU Co., Ltd.", segment: "skincare", gubun: "", email: "", contactEmail: "jmh@jncoceu.com", contactName: "진명훈", instagram: "", phone: "010-2578-0785" },
  { code: "DRS7729", brand: "에이치앤엘바이오", segment: "skincare", gubun: "", email: "connect@drschiller.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DUA8841", brand: "듀얼테트라", segment: "skincare", gubun: "홈디바이스", email: "customercare@cura-pulse.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DUC3548", brand: "디유코스메틱", segment: "beauty", gubun: "메이크업", email: "uj854@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "DYC7852", brand: "(주)디와이코스메틱", segment: "skincare", gubun: "", email: "dy-cos@daum.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "EAS4285", brand: "이지템", segment: "skincare", gubun: "홈디바이스", email: "sales@easytem.co.kr", contactEmail: "yjlee@easytem.co.kr", contactName: "이윤주", instagram: "", phone: "010-9163-1242" },
  { code: "EBI7175", brand: "EBIN KOREA", segment: "skincare", gubun: "스킨케어/바디", email: "ebinkorea@ebinnewyork.com", contactEmail: "", contactName: "", instagram: "@ebinkorea", phone: "" },
  { code: "ECO2048", brand: "주식회사 에코마인", segment: "skincare", gubun: "", email: "", contactEmail: "ecomine@ecomine.co.kr", contactName: "안성재", instagram: "", phone: "010-7192-2887" },
  { code: "ECO4424", brand: "미영씨앤씨", segment: "skincare", gubun: "헤어", email: "ecomine@ecomine.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ECO4769", brand: "에코문도 코리아", segment: "skincare", gubun: "", email: "korea@ecomundo.eu", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "EDE4532", brand: "주식회사 이든팜", segment: "skincare", gubun: "", email: "eden@edencos.co.kr", contactEmail: "dwkim@edencos.co.kr", contactName: "김덕우", instagram: "", phone: "010-7476-7017" },
  { code: "EII2704", brand: "이아이오(L-H02) / 누이브(L-H03)", segment: "skincare", gubun: "더마", email: "eiio@cosmetina.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "EKC9325", brand: "에시컬코리아 코스메틱 (EK COS)", segment: "skincare", gubun: "", email: "butiq99@naver.com", contactEmail: "ek-cosmetics@naver.com", contactName: "김정훈", instagram: "", phone: "010-8527-8589" },
  { code: "EKC9710", brand: "EK COS (ETHICAL KOREA COSMETICS CO., LTD / (주)에씨컬코리아코스메틱스); Cosmetic Brands: MULDREAM | YEPRE", segment: "skincare", gubun: "", email: "", contactEmail: "muldreamofficial@naver.com / ek-cosmetics@naver.com", contactName: "김혜진", instagram: "", phone: "010-7141-9757" },
  { code: "ELI5504", brand: "(주) 엘림텍", segment: "skincare", gubun: "", email: "sales@elimtek.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ELL9888", brand: "(주)본플렉스", segment: "skincare", gubun: "헤어", email: "ellaplex@ellaplex.com", contactEmail: "bonplex@naver.com", contactName: "최인숙", instagram: "@bonplex_official", phone: "010-6710-3368" },
  { code: "ENG5168", brand: "크레모랩", segment: "skincare", gubun: "스킨케어", email: "ayuan@samwhan.co.kr", contactEmail: "", contactName: "", instagram: "@cremorlab_kr", phone: "" },
  { code: "ENT3068", brand: "주식회사 엔스", segment: "skincare", gubun: "", email: "enthsales@enth.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "EPI5537", brand: "epielle", segment: "skincare", gubun: "스킨케어", email: "online@epielle.com", contactEmail: "jeongdaum@privatelabelworks.com", contactName: "정 다 움", instagram: "@www.instagram.com", phone: "010-2685-6293" },
  { code: "ERT2767", brand: "erty. (DERMA PROFESSIONAL) / (주)에르떠코리아", segment: "skincare", gubun: "", email: "", contactEmail: "ceo@ertykorea.com", contactName: "최제훈", instagram: "", phone: "010-3910-5555" },
  { code: "ERT7052", brand: "주식회사 에르띠코리아", segment: "skincare", gubun: "더마", email: "ertykorea@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ESG4161", brand: "ESTRÎGINE / 주식회사 아톨로", segment: "skincare", gubun: "", email: "", contactEmail: "attollo.oes@gmail.com", contactName: "권순원", instagram: "", phone: "010-8607-1831" },
  { code: "EST4136", brand: "주식회사 에스테르", segment: "skincare", gubun: "스킨케어", email: "estercos@daum.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ETE2837", brand: "ETELANC (에텔랑 화장품)", segment: "skincare", gubun: "", email: "", contactEmail: "etelanc@etelanc.com", contactName: "김헌준", instagram: "@etelanc_heonjun", phone: "010-3133-3536" },
  { code: "ETE6480", brand: "에텔랑", segment: "skincare", gubun: "스킨케어", email: "thyme9905@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ETG9498", brand: "L-E03: Tender garden 텐더가든 / L-E04: BELDORA 벨도라", segment: "skincare", gubun: "스킨케어", email: "vglobal@vplatform.kr", contactEmail: "", contactName: "", instagram: "@tender_garden_official", phone: "" },
  { code: "EUC8348", brand: "유씨엘 주식회사", segment: "skincare", gubun: "", email: "UCL.Global@e-ucl.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "EXO5620", brand: "exomera", segment: "skincare", gubun: "", email: "miocid@widemore.co.kr", contactEmail: "mynaomi78@naver.com", contactName: "신난희", instagram: "@exomera.kor", phone: "010-9784-0603" },
  { code: "EYE3045", brand: "EYECANDY (아이캔디)", segment: "skincare", gubun: "헤어", email: "stephen@jworksext.co.kr", contactEmail: "", contactName: "", instagram: "@eyecandy_co_kr", phone: "" },
  { code: "EZE8225", brand: "주식회사 에스겔코스메틱", segment: "skincare", gubun: "", email: "ezekielcos@hanmail.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "FAB7677", brand: "페이블", segment: "skincare", gubun: "향수", email: "cs@atnature.co.kr", contactEmail: "", contactName: "", instagram: "@fableperfume", phone: "" },
  { code: "FAC7015", brand: "Faye Crafts Co., Ltd", segment: "skincare", gubun: "", email: "", contactEmail: "13736911217@163.com", contactName: "Mia Jin", instagram: "@miajinyueji", phone: "+86 13736911217" },
  { code: "FAF8744", brand: "FACE FACTORY", segment: "skincare", gubun: "홈디바이스", email: "marketing@cubist.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "FAR9160", brand: "파믹", segment: "skincare", gubun: "스킨케어", email: "snr@acefarminc.com", contactEmail: "", contactName: "", instagram: "@farmic.official", phone: "" },
  { code: "FLE5048", brand: "flexdi (flexdi International) - Innovative Led Display Company", segment: "skincare", gubun: "", email: "", contactEmail: "flexdikorea@gmail.com", contactName: "김원일", instagram: "", phone: "010-7154-6629" },
  { code: "FLO7349", brand: "아롬컴퍼니", segment: "skincare", gubun: "", email: "florencekim04@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "FMK5277", brand: "fmk 에프엠케이", segment: "skincare", gubun: "더마", email: "fmk@gfcos.co.kr", contactEmail: "", contactName: "", instagram: "@fmkbeauty_kr", phone: "" },
  { code: "FOE2413", brand: "주식회사 라오가닉", segment: "skincare", gubun: "이너뷰티", email: "irene@laorganic.co.kr", contactEmail: "", contactName: "", instagram: "@foellie_official", phone: "" },
  { code: "FON1633", brand: "포뉴레브", segment: "skincare", gubun: "향수", email: "info@fonewlev.com", contactEmail: "info@fonewlev.com", contactName: "김진주", instagram: "@fonewlev.official", phone: "010-9466-2040" },
  { code: "FOR1828", brand: "FORMECELL(포미셀)", segment: "skincare", gubun: "더마", email: "misun5508@naver.com", contactEmail: "", contactName: "", instagram: "@formecell_official", phone: "" },
  { code: "FOR7344", brand: "(주)씨피코스메틱", segment: "skincare", gubun: "", email: "", contactEmail: "jamessohn@cpcosmetic.co.kr", contactName: "손지범", instagram: "", phone: "010-7415-1471" },
  { code: "FRA3429", brand: "(주)바이오센서연구소", segment: "skincare", gubun: "스킨케어", email: "franz@biosensorlab.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "FRC2734", brand: "From:Cella / DASHU / Daleaf (ChromaX Co., Ltd)", segment: "skincare", gubun: "헤어", email: "dashu.jungjoo@gmail.com", contactEmail: "", contactName: "", instagram: "@dashu_official", phone: "" },
  { code: "GCI6418", brand: "GCV iDEAL", segment: "skincare", gubun: "", email: "", contactEmail: "shailesh.gadre@gcvlife.in / shailesh.gadre@gcvideal.com", contactName: "Shailesh Gadre", instagram: "", phone: "+91 9867324097" },
  { code: "GCT8960", brand: "Guangdong Candear Technology Innovation Co.,Ltd", segment: "skincare", gubun: "", email: "", contactEmail: "2932410479@qq.com", contactName: "Vicky Wen 温杏婷", instagram: "", phone: "+86-13431974599" },
  { code: "GEN8322", brand: "GENOSS / (주)제노스", segment: "skincare", gubun: "", email: "", contactEmail: "jhbae@genoss.com", contactName: "배종훈", instagram: "", phone: "010-4154-5922" },
  { code: "GFC2498", brand: "GFC 생명과학 (GFC Life Science)", segment: "skincare", gubun: "", email: "", contactEmail: "kh.kim@gfcos.co.kr", contactName: "김경혜", instagram: "", phone: "010-8541-5073" },
  { code: "GLA5123", brand: "GLADDENER", segment: "skincare", gubun: "", email: "", contactEmail: "team@gladdener.com", contactName: "SEO, KANG HYUK", instagram: "", phone: "010-337-9461" },
  { code: "GLI8012", brand: "GUANGZHOU LVFANGZHOU INDUSTRIAL CO.,LTD", segment: "skincare", gubun: "", email: "lvfangzhou@126.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "GLS4364", brand: "GLOW SKIN (Glow The Skin)", segment: "skincare", gubun: "", email: "", contactEmail: "glowsk@glowsk.co.kr", contactName: "박찬율", instagram: "", phone: "010-3353-7182" },
  { code: "GMM2144", brand: "GMC Med", segment: "skincare", gubun: "", email: "info@gmcmed.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "GNI8576", brand: "(주)지앤아이코스메틱", segment: "skincare", gubun: "", email: "gnicos@gnicos.co.kr", contactEmail: "jsumin@gnicos.co.kr", contactName: "지수민", instagram: "", phone: "010-7677-3693" },
  { code: "GOX5705", brand: "지구의 온도 G9ONDO", segment: "skincare", gubun: "바디/향수", email: "tomato2526@nate.com", contactEmail: "", contactName: "", instagram: "@g9ondo_beauty", phone: "" },
  { code: "GOY8667", brand: "고요이 GOYOYI", segment: "skincare", gubun: "향수", email: "hello@goyoyi.com", contactEmail: "", contactName: "", instagram: "@goyoyi.official", phone: "" },
  { code: "GRA3557", brand: "부드와서울", segment: "skincare", gubun: "스킨케어", email: "grandidier_official@naver.com", contactEmail: "", contactName: "-", instagram: "@grandidier_official", phone: "" },
  { code: "GRE2804", brand: "그린코스 주식회사", segment: "skincare", gubun: "", email: "help@green-cos.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "GSL1688", brand: "제이앤지코스메틱(주)", segment: "skincare", gubun: "스킨케어", email: "jngcos@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "GSN4363", brand: "GUANGZHOU SIYU NON-WOVEN PRODUCTS CO., LTD.", segment: "skincare", gubun: "", email: "1102020670@qq.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "GYB9418", brand: "GYBIO (GLOBAL YOUTH SOLUTION)", segment: "skincare", gubun: "", email: "INFO@GYBIO.CO.KR", contactEmail: "info@gybio.co.kr", contactName: "Anna Lee", instagram: "", phone: "010-4727-9358" },
  { code: "HAN1256", brand: "HANCHUNG (한청 메디컬)", segment: "skincare", gubun: "", email: "", contactEmail: "justin_park@hanchung.biz", contactName: "Justin Park", instagram: "", phone: "010-9366-1168" },
  { code: "HAN2699", brand: "Hansol (Hansol Paper Co., Ltd.)", segment: "skincare", gubun: "", email: "", contactEmail: "sh.an@hansol.com", contactName: "Sang Hyun An", instagram: "", phone: "010-9591-2026" },
  { code: "HAN8302", brand: "HANJINEYMAY CO.,LTD", segment: "skincare", gubun: "스킨케어", email: "official@hanjineymay.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HAP5709", brand: "해피엘앤비", segment: "skincare", gubun: "", email: "happy@happylnb.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HAS5152", brand: "Hanyang S&D / (주)한양에스엔디 / 한양테크(주)", segment: "skincare", gubun: "", email: "", contactEmail: "4177853@naver.com", contactName: "이철형", instagram: "", phone: "010-9134-7853" },
  { code: "HBB2805", brand: "HEBEI BEYRON BIOTECH CO., LTD.", segment: "skincare", gubun: "", email: "jason@beyron.cn", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HBL4068", brand: "HUAXIN BIOTECHNOLOGY CO., LIMITED", segment: "skincare", gubun: "", email: "olwen_z@foxmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HBM7964", brand: "한방미인화장품 HBMIC", segment: "skincare", gubun: "", email: "", contactEmail: "hbmic@hbmic.com", contactName: "안다정", instagram: "", phone: "010-3849-3371" },
  { code: "HEA2412", brand: "헤아림코스메틱", segment: "skincare", gubun: "스킨케어", email: "hearim@hearimcosmetic.com", contactEmail: "", contactName: "", instagram: "@hearimcosmetic", phone: "" },
  { code: "HEA3559", brand: "HE:ARIM", segment: "skincare", gubun: "", email: "", contactEmail: "partner@hearimcosmetic.com", contactName: "이신", instagram: "@hearimcosmetic", phone: "010-8788-6552" },
  { code: "HET5633", brand: "hetras. (Cosmetic & Daily supplies)", segment: "skincare", gubun: "", email: "", contactEmail: "jh.park@hetras.co.kr", contactName: "Joey Park", instagram: "", phone: "010-8685-8075" },
  { code: "HJC4836", brand: "에이치제이코퍼레이션즈 주식회사", segment: "skincare", gubun: "", email: "info@hjcorporations.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HNB8669", brand: "에이치앤비바이오", segment: "skincare", gubun: "", email: "hnb.biomask@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HON3338", brand: "Korea Honey", segment: "skincare", gubun: "스킨케어", email: "sharp-be@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HPN8096", brand: "주식회사 에이치피앤씨", segment: "skincare", gubun: "더마", email: "hpncmall@hpnc.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HSP8836", brand: "홈앤쇼핑", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HUB4840", brand: "휴비스랩", segment: "skincare", gubun: "", email: "info@hubislab.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HUC3993", brand: "휴션", segment: "skincare", gubun: "더마", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HUE5901", brand: "HUEHEAL", segment: "skincare", gubun: "스킨케어", email: "admin@huehea.com", contactEmail: "", contactName: "", instagram: "@hueheal_global", phone: "" },
  { code: "HYC5444", brand: "에이치앤와이 상사", segment: "skincare", gubun: "더마", email: "yehan1@naver.com", contactEmail: "", contactName: "", instagram: "@dr.misimou", phone: "" },
  { code: "ICB7902", brand: "ICON BX (Brand Expansion)", segment: "skincare", gubun: "", email: "", contactEmail: "frances@i-con.co.kr", contactName: "정다원", instagram: "", phone: "010-6636-1585" },
  { code: "ICE1712", brand: "아이셀메디텍", segment: "skincare", gubun: "", email: "www.icelmedi@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ICE4333", brand: "아이스링커 주식회사", segment: "skincare", gubun: "", email: "icelinker@icelinker.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ILL6045", brand: "ILLON CO., LTD", segment: "skincare", gubun: "더마/스킨케어", email: "global@illon.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ILO9445", brand: "(주)순바이오팜", segment: "skincare", gubun: "", email: "", contactEmail: "sales@soonbiopharm.com", contactName: "양지원", instagram: "", phone: "010-2702-0168" },
  { code: "IMA1002", brand: "1010 image+ (이미지 플러스)", segment: "skincare", gubun: "", email: "", contactEmail: "ire70@naver.com", contactName: "김교니", instagram: "", phone: "010-9468-9079" },
  { code: "INB1748", brand: "주식회사 바이비카", segment: "skincare", gubun: "헤어", email: "hello@inbutim.com", contactEmail: "", contactName: "", instagram: "@inbutim_official", phone: "" },
  { code: "ING2955", brand: "(주)아이엔지알 (INGR)", segment: "skincare", gubun: "", email: "", contactEmail: "jinseok.lee@ingr.kr", contactName: "이진석", instagram: "", phone: "010-6283-8113" },
  { code: "INO3792", brand: "INOPRO", segment: "skincare", gubun: "오럴케어", email: "alexander@inopro.us", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "INS5832", brand: "인솔 주식회사", segment: "skincare", gubun: "더마", email: "ninova@in-sol.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "INT8519", brand: "INTERWORK (INTERWORK KOREA Co., Ltd.) / (주)인터워크코리아", segment: "skincare", gubun: "", email: "", contactEmail: "mina@interworkgroup.com", contactName: "최미나", instagram: "", phone: "010-8003-5404" },
  { code: "INX1752", brand: "IN2BIO (주)인투바이오", segment: "skincare", gubun: "", email: "", contactEmail: "in2bio@in2bio.com", contactName: "박수영", instagram: "", phone: "010-3150-1391" },
  { code: "IPR4551", brand: "IPRODUCT", segment: "skincare", gubun: "", email: "", contactEmail: "ceo@iproduct.co.kr", contactName: "이승준", instagram: "", phone: "010-3005-5250" },
  { code: "IRE9024", brand: "(주)이레코스메틱", segment: "skincare", gubun: "스킨케어", email: "irecosmetics@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JAM5460", brand: "자민경", segment: "skincare", gubun: "스킨케어", email: "youjinsuk1@jaminkyung.com", contactEmail: "", contactName: "", instagram: "@jaminkyung_official", phone: "" },
  { code: "JAM7445", brand: "(주)탠코리아", segment: "skincare", gubun: "바디", email: "jamiebronzekr@gmail.com", contactEmail: "", contactName: "", instagram: "@jamie_bronze", phone: "" },
  { code: "JCL1399", brand: "JDN CORPORATION LIMITED", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JCR2085", brand: "제이크리컴퍼니", segment: "skincare", gubun: "더마", email: "jcre@jcrecompany.com", contactEmail: "", contactName: "", instagram: "@lefilleo.official", phone: "" },
  { code: "JDB4181", brand: "㈜제이디바이오", segment: "skincare", gubun: "", email: "info@jdbio.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JIN2855", brand: "JINSIM (진심)", segment: "skincare", gubun: "", email: "", contactEmail: "young@apex-global.org", contactName: "최영운", instagram: "@jinsimskincare", phone: "010-3561-9940" },
  { code: "JIN6197", brand: "Jincostech", segment: "skincare", gubun: "", email: "", contactEmail: "kdh@jincostech.com", contactName: "김동헌", instagram: "", phone: "010-5592-6578" },
  { code: "JKO2875", brand: "JKOSMEC", segment: "skincare", gubun: "스킨케어", email: "sales@jkosmecseoul.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JKS2372", brand: "(주)일진코스메틱", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JNC4737", brand: "닥터펩티", segment: "skincare", gubun: "더마", email: "trade@jncoceu.com", contactEmail: "", contactName: "", instagram: "@dr.pepti", phone: "" },
  { code: "JNJ6445", brand: "(주)제이앤제이", segment: "skincare", gubun: "더마", email: "jnj_25@daum.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JNR2432", brand: "제너랩", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JOY1793", brand: "(주)죠이라이프", segment: "skincare", gubun: "", email: "export@jlife1.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JSS3164", brand: "주식회사 제이에스사이언스", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JTC2993", brand: "(주)제이티", segment: "skincare", gubun: "", email: "contact@jtcosmetic.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JTP8999", brand: "JTP 제주테크노파크 청정바이오사업본부 (바이오센터 / 화장품사업팀) / COSMETIC CERT JEJU", segment: "skincare", gubun: "", email: "", contactEmail: "cosmetics@jejutp.or.kr", contactName: "", instagram: "", phone: "" },
  { code: "JUL7836", brand: "줄라이 모닝", segment: "skincare", gubun: "바디/헤어", email: "clubparty1003@gmail.com", contactEmail: "", contactName: "", instagram: "@wearejulymorning", phone: "" },
  { code: "JUN7488", brand: "(주) 정동산업", segment: "skincare", gubun: "", email: "duzon@jungdong.biz", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JUN8221", brand: "주식회사 정코스메틱", segment: "skincare", gubun: "더마", email: "jungco@jungco.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KBC4961", brand: "KBH CARE ((주)KBH CARE)", segment: "skincare", gubun: "", email: "", contactEmail: "naza@kbhcare.com", contactName: "Naza", instagram: "", phone: "010-2270-6646" },
  { code: "KBH2681", brand: "(주)케이비에이치케어", segment: "skincare", gubun: "더마", email: "kbhcare@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KIN1325", brand: "킨뮬러", segment: "skincare", gubun: "더마", email: "beauty@kinmula.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KKI8749", brand: "이연물산", segment: "skincare", gubun: "", email: "kkim09@nate.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KME8256", brand: "케이투메디텍", segment: "skincare", gubun: "", email: "info@k2meditech.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KMX2763", brand: "K2 Meditech", segment: "skincare", gubun: "", email: "", contactEmail: "sales2@k2meditech.com", contactName: "최범준", instagram: "", phone: "010-5195-1120" },
  { code: "KOC2633", brand: "KOCOSTAR", segment: "skincare", gubun: "스킨케어", email: "export@kocostar.com", contactEmail: "an.ji@kocostar.com", contactName: "안종진", instagram: "@kocostar", phone: "010-8705-5313" },
  { code: "KON2746", brand: "KONAD코나드", segment: "beauty", gubun: "메이크업", email: "konadkorea@konadnail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KON5156", brand: "주식회사 케이원파마", segment: "skincare", gubun: "", email: "konepharma@konepharma.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KOW1793", brand: "(주)코윈바이오", segment: "skincare", gubun: "더마", email: "mesablue@kowinbio.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KPC9113", brand: "KPCOS", segment: "skincare", gubun: "스킨케어", email: "kyulgoun@kyulgoun.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KWA9938", brand: "케이웨이컴퍼니(주) (KWAY Company)", segment: "skincare", gubun: "", email: "", contactEmail: "soljo310@kwaycompany.com", contactName: "조솔", instagram: "", phone: "010-6830-4130" },
  { code: "KYU6556", brand: "KYUNGLAB", segment: "skincare", gubun: "더마", email: "info@ssmb.vn", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LAN3776", brand: "LANNUE", segment: "skincare", gubun: "스킨케어", email: "lannue.cos@gmail.com", contactEmail: "", contactName: "", instagram: "@lannue.official", phone: "" },
  { code: "LAN4077", brand: "주식회사 랑벨", segment: "skincare", gubun: "더마", email: "official@lanbelle.com", contactEmail: "shoo.noh@lanbelle.com", contactName: "노수란", instagram: "@lanbelle.official", phone: "010-3662-0227" },
  { code: "LAN7173", brand: "랑느 코스메틱 (Lannue Cosmetic)", segment: "skincare", gubun: "", email: "", contactEmail: "sunmi.park@lannue.kr", contactName: "박선미", instagram: "", phone: "010-7535-6211" },
  { code: "LAV2337", brand: "LAVIUS", segment: "skincare", gubun: "", email: "", contactEmail: "lavius@lavius.co.kr", contactName: "박현빈", instagram: "@lavius_official", phone: "010-5439-0226 / 010-5680-2672" },
  { code: "LBX9151", brand: "2L Bio", segment: "skincare", gubun: "", email: "", contactEmail: "sales@2lbio.com", contactName: "임예은", instagram: "", phone: "010-2022-5343" },
  { code: "LEA9053", brand: "주식회사 리더스코스메틱", segment: "skincare", gubun: "", email: "odem@leaderscosmetics.com", contactEmail: "kimdy@leaderscosmetics.com", contactName: "김도연", instagram: "", phone: "010-4632-1626" },
  { code: "LEB5369", brand: "르베라쥬", segment: "skincare", gubun: "스킨케어", email: "lebelage@lebelage.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LEB7452", brand: "LEBELAGE / HEEYUL", segment: "skincare", gubun: "", email: "", contactEmail: "cidcos3292@naver.com", contactName: "주수현", instagram: "", phone: "010-7166-4566" },
  { code: "LEC9555", brand: "LECOS", segment: "skincare", gubun: "", email: "sales@lecospack.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LEF8448", brand: "leterie fru& (ANOETIC); 주식회사 데일리컴퍼니", segment: "skincare", gubun: "", email: "", contactEmail: "info@anoetic.kr", contactName: "박용준", instagram: "@anoetic_kr", phone: "010-7573-0486" },
  { code: "LIC5688", brand: "리꼼 코스메틱", segment: "skincare", gubun: "더마", email: "minwoolee@limetree.kr", contactEmail: "", contactName: "", instagram: "@licorne_cosmetics", phone: "" },
  { code: "LIE1085", brand: "(주)리베코스", segment: "skincare", gubun: "", email: "tim@saenggreen.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LII5953", brand: "리타", segment: "skincare", gubun: "스킨케어", email: "liita@proving-grounds.co.kr", contactEmail: "", contactName: "", instagram: "@liita.official", phone: "" },
  { code: "LIN1250", brand: "LINDSAY&COS Inc.", segment: "skincare", gubun: "스킨케어", email: "sales@lindsay.co.kr", contactEmail: "sales@lindsay.co.kr", contactName: "도미란", instagram: "@lindsay_shop", phone: "010-7142-4972" },
  { code: "LIN5253", brand: "엑소블랑", segment: "skincare", gubun: "홈디바이스", email: "info@linkusglobal.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LIN9472", brand: "(주) 진코스텍", segment: "skincare", gubun: "", email: "lsw@jincostech.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LIS2301", brand: "(주)리쎄코리아", segment: "skincare", gubun: "스킨케어", email: "lisse@lisse.co.kr", contactEmail: "lisse@lisse.co.kr / lissekor@naver.com", contactName: "Jenny Kim", instagram: "@dumidang_official", phone: "010-2886-9370" },
  { code: "LIT8508", brand: "닥터바이오 & 티블레스", segment: "skincare", gubun: "스킨케어", email: "global_sales@rokcorp.co.kr", contactEmail: "", contactName: "", instagram: "@dr.bio_official", phone: "" },
  { code: "LMB5036", brand: "LINK METOO BIO-TECHNOLOGY DALIAN CO.,LTD", segment: "skincare", gubun: "", email: "1013636360@qq.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LOG6648", brand: "로그인 포레스트 (유나뷰티랩)", segment: "skincare", gubun: "향수", email: "info@loginforest.com", contactEmail: "", contactName: "", instagram: "@loginforest_official", phone: "" },
  { code: "LOO2925", brand: "(주)승건코스메틱스", segment: "skincare", gubun: "스킨케어", email: "lppm47@naver.com", contactEmail: "", contactName: "", instagram: "@loobee_official", phone: "" },
  { code: "LPH4940", brand: "LPHYSIO Co.,Ltd / 주식회사 엘피지오", segment: "skincare", gubun: "", email: "", contactEmail: "zoe.hong@lphysio.co.kr", contactName: "홍지은", instagram: "", phone: "010-7745-0156" },
  { code: "LRO4793", brand: "엘로드 (lroad)", segment: "skincare", gubun: "", email: "", contactEmail: "namsan@lroad.co.kr", contactName: "남상찬", instagram: "", phone: "010-4176-7984" },
  { code: "LUA6383", brand: "Lua The Company (주)루아더컴퍼니", segment: "skincare", gubun: "", email: "", contactEmail: "official@luathe.com", contactName: "김명준", instagram: "", phone: "010-4037-1424" },
  { code: "LUN3517", brand: "lunarience (루나리언스)", segment: "skincare", gubun: "", email: "", contactEmail: "ljhdandy@gmail.com", contactName: "이종현", instagram: "", phone: "010-3820-7990" },
  { code: "LUV3331", brand: "주식회사 바이잇", segment: "skincare", gubun: "스킨케어", email: "export@luvum.co.kr", contactEmail: "", contactName: "", instagram: "@luvum_official", phone: "" },
  { code: "LUV6946", brand: "Luvum", segment: "skincare", gubun: "", email: "", contactEmail: "jhl0615@luvum.co.kr", contactName: "이정훈", instagram: "", phone: "010-6525-9325" },
  { code: "LUX4669", brand: "유니티", segment: "skincare", gubun: "스킨케어", email: "luxevo@luxevo.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "LYL5125", brand: "릴릴", segment: "skincare", gubun: "스킨케어", email: "christin@rewindlab.co.kr", contactEmail: "", contactName: "", instagram: "@lylyl_official", phone: "" },
  { code: "MAS2234", brand: "MAKE SOUL", segment: "beauty", gubun: "메이크업", email: "jslee@make-soul.co.kr", contactEmail: "", contactName: "", instagram: "@makesoul_official", phone: "" },
  { code: "MAX2453", brand: "MAXhyd (맥스하이드)", segment: "skincare", gubun: "", email: "", contactEmail: "cosmetics@maxhyd.com", contactName: "염지예", instagram: "", phone: "010-7732-0636" },
  { code: "MAY1753", brand: "(주)제이지에스헬스큐어", segment: "skincare", gubun: "스킨케어", email: "mayyoung@mayyoung.kr", contactEmail: "jgshealthcure@gmail.com", contactName: "", instagram: "", phone: "010-9259-6218" },
  { code: "MAY3296", brand: "주식회사 미팜", segment: "skincare", gubun: "", email: "support@maypharm.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MAY7254", brand: "MAYPHARM", segment: "skincare", gubun: "", email: "", contactEmail: "lianmei@maypharm.co.kr", contactName: "이렌미", instagram: "", phone: "010-7583-6638" },
  { code: "MCP8743", brand: "matthew chang perfumes", segment: "skincare", gubun: "향수", email: "contact@matthewchangperfumes.com", contactEmail: "david@matthewchangperfumes.com", contactName: "David Koh", instagram: "@matthewchangperfumes", phone: "010-6865-6966" },
  { code: "MDW4436", brand: "(주) 엠디무역", segment: "skincare", gubun: "헤어", email: "mdtrad@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MED2140", brand: "메딕콘", segment: "skincare", gubun: "홈디바이스", email: "medicon@medicon.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MED3965", brand: "(주)엠피컴퍼니", segment: "skincare", gubun: "더마", email: "jungye@medipair.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MED7986", brand: "MEDICON (ODM/OEM 생산제조)", segment: "skincare", gubun: "", email: "", contactEmail: "lhc@medicon.co.kr", contactName: "이호철", instagram: "", phone: "010-5138-5392" },
  { code: "MEL5395", brand: "MELKA", segment: "skincare", gubun: "", email: "woojinkim88@daum.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MES3940", brand: "주식회사 메조팜", segment: "skincare", gubun: "더마", email: "purple9260@hnamail.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MIE1829", brand: "MISS EDE (미스이디 / EDE FARM)", segment: "skincare", gubun: "", email: "", contactEmail: "jm4170@naver.com", contactName: "박종무", instagram: "", phone: "010-2367-0650" },
  { code: "MIM7619", brand: "MIMO CO., LTD.", segment: "skincare", gubun: "네일", email: "sales@mimonail.com", contactEmail: "ben@veterannails.com / info@veterannails.com", contactName: "문형오", instagram: "", phone: "010-9569-9289" },
  { code: "MIS3016", brand: "컬러딥", segment: "beauty", gubun: "메이크업", email: "min@miskos.co.kr", contactEmail: "", contactName: "", instagram: "@colordeep_korea", phone: "" },
  { code: "MIS3484", brand: "(주)미성메탈", segment: "skincare", gubun: "뷰티소품", email: "jkhan@misunggc.co.k", contactEmail: "jylee@misunggc.co.kr", contactName: "이지윤", instagram: "", phone: "010-3244-9345" },
  { code: "MIS7073", brand: "MISSMORE (TOTAL BEAUTY) / 주식회사 미스모아", segment: "skincare", gubun: "", email: "", contactEmail: "simo0918@naver.com", contactName: "심호민", instagram: "", phone: "010-7223-0918" },
  { code: "MJC1556", brand: "(주)미진화장품", segment: "skincare", gubun: "", email: "mijin_kor@mjcare.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MLL5162", brand: "MLAY INTERNATIONAL LIMITED", segment: "skincare", gubun: "홈디바이스", email: "mt@mlays.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MOE3064", brand: "moev (MOEV International Co.,Ltd.) - K-Haircare Brand", segment: "skincare", gubun: "", email: "", contactEmail: "ck@innovinekorea.com / sales@moevhair.kr", contactName: "Kyuseok Choi", instagram: "", phone: "010-9403-9806" },
  { code: "MOM2718", brand: "MOMIX / 모믹스", segment: "skincare", gubun: "", email: "", contactEmail: "sr1151@naver.com / sales@momix.co.kr", contactName: "성서럼", instagram: "", phone: "010-8691-1151" },
  { code: "MOM4344", brand: "momeii / (주)뷰템 (Beautem co., Ltd)", segment: "skincare", gubun: "", email: "", contactEmail: "ychoi@beautemco.com", contactName: "최영지", instagram: "", phone: "010-9114-0543" },
  { code: "MOM6933", brand: "모메이", segment: "beauty", gubun: "메이크업", email: "beautemco@gmail.com", contactEmail: "", contactName: "", instagram: "@momeii_official", phone: "" },
  { code: "MOO8377", brand: "주식회사 스타힐스코스메틱", segment: "skincare", gubun: "헤어", email: "hmcos@naver.com", contactEmail: "", contactName: "", instagram: "@moo100_life", phone: "" },
  { code: "MSN1248", brand: "MEDI SECTION NO.", segment: "skincare", gubun: "", email: "global@inot-meditech.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MTP7548", brand: "주식회사 모티프커뮤니케이션", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "MUL2722", brand: "Muldream (물드림)", segment: "skincare", gubun: "", email: "", contactEmail: "muldreamofficial@naver.com", contactName: "김혜진", instagram: "", phone: "010-7141-9757" },
  { code: "MYS9900", brand: "명성코퍼레이션 (MYUNG SUNG CORP.)", segment: "skincare", gubun: "", email: "", contactEmail: "us0103@imyungsung.co.kr", contactName: "정은용", instagram: "", phone: "010-2393-1998" },
  { code: "NAN7780", brand: "주식회사 나노실리칸첨단소재", segment: "skincare", gubun: "", email: "info@nanobrick.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NAN9129", brand: "(주)나노바이오시스템", segment: "skincare", gubun: "", email: "mkt@nanobiosystem.co.kr", contactEmail: "ksw@nanobiosystem.co.kr", contactName: "김송원", instagram: "", phone: "010-2078-6077" },
  { code: "NAS1215", brand: "NASCOR (나스코)", segment: "skincare", gubun: "", email: "", contactEmail: "Cael.Kim@nascor.co.kr", contactName: "김연삼", instagram: "", phone: "010-9299-0123" },
  { code: "NAT2202", brand: "NATUZEN CO., LTD.,", segment: "skincare", gubun: "", email: "natuzensales@natuzen.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NAT6553", brand: "네이처파마", segment: "skincare", gubun: "", email: "rejucell@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NEE6112", brand: "(주)온궁", segment: "skincare", gubun: "", email: "leesanghoong@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NEO1081", brand: "(주) 네오제네시스", segment: "skincare", gubun: "", email: "info@neogenesis.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NEX9104", brand: "주식회사 넥슨화장품", segment: "skincare", gubun: "스킨케어", email: "", contactEmail: "gsales@leeblese.com", contactName: "마디나", instagram: "", phone: "010-6581-6364" },
  { code: "NOC8436", brand: "NINE ONE COSMEDI (Cosmetic Science & Technology)", segment: "skincare", gubun: "", email: "", contactEmail: "OBD@91cosmedi.com", contactName: "심주호", instagram: "", phone: "010-2247-8729" },
  { code: "NOT1569", brand: "주식회사 퍼플링크", segment: "skincare", gubun: "바디", email: "eth@purplelink.kr", contactEmail: "eth@purplelink.kr", contactName: "엄태한", instagram: "@not4u_korea", phone: "010-9457-2952" },
  { code: "NOV7252", brand: "Nove Beauty (Shenzhen Nove Technology)", segment: "skincare", gubun: "", email: "", contactEmail: "admin@novebeauty.cn", contactName: "Pan Liu", instagram: "", phone: "Tel / WhatsApp: +86 137 1156 1048" },
  { code: "NPL4110", brand: "대봉엘에스(주) (천연물소재응용연구소 / Natural Products Laboratory)", segment: "skincare", gubun: "", email: "", contactEmail: "jm.heo@daebongls.co.kr", contactName: "허정미", instagram: "", phone: "010-4139-4080" },
  { code: "NRX1505", brand: "뉴런", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NSC5176", brand: "㈜나산기업", segment: "skincare", gubun: "", email: "nasan@nscolor.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NUC8063", brand: "U'NUCO [유누꼬]", segment: "skincare", gubun: "", email: "", contactEmail: "unuco@unuco.co.kr", contactName: "문찬수", instagram: "", phone: "010-4116-6145" },
  { code: "NUL4052", brand: "Nuon LLC", segment: "skincare", gubun: "", email: "info@nuonmedical.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NUN6361", brand: "NUNA", segment: "skincare", gubun: "스킨케어", email: "contact@nunabeautylab.com", contactEmail: "", contactName: "", instagram: "@nuna_beautylab", phone: "" },
  { code: "NUN9416", brand: "nunabeautylab", segment: "skincare", gubun: "", email: "", contactEmail: "lesya@nunabeautylab.com", contactName: "Lesya", instagram: "", phone: "+79197277882" },
  { code: "NUR7809", brand: "(주)아이테크", segment: "skincare", gubun: "", email: "nurieye@daum.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NUS6801", brand: "누셀리크", segment: "skincare", gubun: "더마", email: "soisintl.biz@gmail.com", contactEmail: "", contactName: "", instagram: "@nuselique_official", phone: "" },
  { code: "NUT4893", brand: "(주)뉴트리케어", segment: "skincare", gubun: "", email: "global2m@nutricare.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "OAV7049", brand: "채널스완", segment: "skincare", gubun: "스킨케어", email: "kbeauty@oavo.kr", contactEmail: "kbeauty@oavo.kr", contactName: "Ryan / Ji Hwan Kim", instagram: "@oavo.global", phone: "010-5374-1886" },
  { code: "ODM1757", brand: "(주)아우딘퓨쳐스(K-Beauty ODM/OEM)", segment: "skincare", gubun: "", email: "kmpark@outinco.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ODS4604", brand: "ODSY", segment: "skincare", gubun: "스킨케어", email: "hello@odsycoltd.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "OFB5721", brand: "OFBASE", segment: "skincare", gubun: "스킨케어", email: "william@eyesomekorea.co.kr", contactEmail: "", contactName: "", instagram: "@ofbase_official", phone: "" },
  { code: "OFF2653", brand: "오프뷰티", segment: "skincare", gubun: "", email: "offbeauty@qandbintl.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "OHA2773", brand: "(주) 유나이티드앤글로벌", segment: "skincare", gubun: "스킨케어", email: "ohave@unitednglobal.com", contactEmail: "", contactName: "", instagram: "@ohave.official", phone: "" },
  { code: "OIO5202", brand: "OIOSY / MOBO / MUA HOLD (여유협동조합)", segment: "skincare", gubun: "", email: "", contactEmail: "deunerang@naver.com", contactName: "정지은", instagram: "", phone: "010-5707-0210" },
  { code: "OMI8517", brand: "오미티드", segment: "skincare", gubun: "스킨케어", email: "admin@omitted.kr", contactEmail: "", contactName: "", instagram: "@omittedofficial", phone: "" },
  { code: "ONE3267", brand: "ONE BEAUTY (ONE BEAUTY Technology Co., Ltd)", segment: "skincare", gubun: "", email: "", contactEmail: "John@onebeauty.com.cn", contactName: "Eve Wang", instagram: "", phone: "+86-13457559424" },
  { code: "ONP6693", brand: "K-ONE PHARMA", segment: "skincare", gubun: "", email: "", contactEmail: "lynn@konepharma.co.kr", contactName: "LYNN LEE", instagram: "", phone: "010-3077-1195" },
  { code: "ORE8741", brand: "(주)오래온라이프사이언스", segment: "skincare", gubun: "", email: "info@oreon.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ORL4805", brand: "메타폴라아로마(주)", segment: "skincare", gubun: "", email: "inform@orlic.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ORP8397", brand: "ORANGE PACK (오렌지팩)", segment: "skincare", gubun: "", email: "", contactEmail: "sales@orange-pack.co.kr", contactName: "김병호", instagram: "", phone: "010-3674-3271" },
  { code: "OSE2444", brand: "주식회사 오션스인터내셔널", segment: "beauty", gubun: "스킨케어/메이크업", email: "oseans@oseansint.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "OVE1049", brand: "주식회사 오버랩스", segment: "skincare", gubun: "스킨케어", email: "business@overlaps.co.kr", contactEmail: "", contactName: "", instagram: "@overlaps.official", phone: "" },
  { code: "OXY1181", brand: "코이즈", segment: "skincare", gubun: "더마", email: "mkt@oxyfacial.com", contactEmail: "coizmkt@gmail.com", contactName: "이경선", instagram: "", phone: "010-8909-4714" },
  { code: "PAL6828", brand: "palette (팔레트)", segment: "skincare", gubun: "", email: "", contactEmail: "by0472@palettecorp.kr", contactName: "윤은희", instagram: "", phone: "010-2796-6733" },
  { code: "PAM7883", brand: "PAMS (pamsbnb)", segment: "skincare", gubun: "", email: "", contactEmail: "alice@pamsbnb.com", contactName: "김영언", instagram: "@pamscosmetics_global", phone: "010-7231-6209 / 010-4844-3887" },
  { code: "PAM9673", brand: "팜스비앤비", segment: "skincare", gubun: "", email: "marketing@pamsbnb.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PDR2377", brand: "(주)피더린", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "정춘수", instagram: "", phone: "010-3220-6031" },
  { code: "PEO9710", brand: "PEOPLE&CO / (주)피플앤코", segment: "skincare", gubun: "", email: "", contactEmail: "peoplenco@daum.net", contactName: "오권석", instagram: "", phone: "010-4734-5991" },
  { code: "PFN4500", brand: "주식회사 피에프네이처", segment: "skincare", gubun: "", email: "marketing@pfnature.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PHH2849", brand: "피에이치하비", segment: "skincare", gubun: "스킨케어", email: "phhubby@phhubby.com", contactEmail: "", contactName: "", instagram: "@phhubby_official", phone: "" },
  { code: "PIC2196", brand: "Picasso (CEZANNE / SUSAN PACIFIC)", segment: "skincare", gubun: "", email: "", contactEmail: "seongsu@picasso.co.kr", contactName: "안성수", instagram: "", phone: "010-4115-2917" },
  { code: "PIL2653", brand: "(주)필코코스팜", segment: "skincare", gubun: "더마", email: "pilko@pilko.org", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PIN3133", brand: "핑키코스메틱", segment: "skincare", gubun: "스킨케어", email: "pinky@pinkycosmetic.kr", contactEmail: "", contactName: "", instagram: "@pinkycosmetic_official", phone: "" },
  { code: "PIN5125", brand: "(주)피노젠", segment: "skincare", gubun: "스킨케어/이너뷰티", email: "pinogen@pinogen.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PIX3892", brand: "픽셀퓨어", segment: "skincare", gubun: "스킨케어", email: "tftrading@pixelpure.com", contactEmail: "tftrading@pixelpure.com", contactName: "", instagram: "@pixelpure_official", phone: "13021120063" },
  { code: "PLA2690", brand: "PLANIT 147 (company of HK Kolmar)", segment: "skincare", gubun: "", email: "", contactEmail: "agneschoi@kolmar.co.kr", contactName: "최경숙", instagram: "", phone: "010-4899-5855" },
  { code: "PLA4328", brand: "플래닛147", segment: "skincare", gubun: "", email: "hello@planit147.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PLA7521", brand: "프랜드", segment: "skincare", gubun: "", email: "pland1590@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PLE4784", brand: "주식회사 라피끄", segment: "skincare", gubun: "스킨케어", email: "cs@rafiqcosmetics.com", contactEmail: "", contactName: "", instagram: "@plentyplant.official", phone: "" },
  { code: "POL2097", brand: "(주)더제이알", segment: "skincare", gubun: "스킨케어", email: "thejrinc17@gmail.com", contactEmail: "", contactName: "", instagram: "@beverlyhillspoloclub_kr", phone: "" },
  { code: "POP1821", brand: "POWER PLAYER (파워플레이어)", segment: "skincare", gubun: "", email: "", contactEmail: "cwo@powerplayer.co.kr", contactName: "정유진", instagram: "", phone: "010-4251-1516" },
  { code: "PRI9857", brand: "(주)프리모리스인터내셔널", segment: "skincare", gubun: "", email: "hnkim@primoris.co.kr", contactEmail: "sylee@primoris.co.kr", contactName: "이소연", instagram: "", phone: "010-7181-8749" },
  { code: "PRN1009", brand: "파란네일", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PUR5517", brand: "주식회사 라메디텍", segment: "skincare", gubun: "홈디바이스", email: "puraxel@lameditech.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PUR8924", brand: "퓨어앤텍(주)", segment: "skincare", gubun: "", email: "sales@purentechkorea.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "PUS6170", brand: "pushthelever", segment: "skincare", gubun: "", email: "", contactEmail: "pushthelever@pushthelever.com", contactName: "서희강", instagram: "", phone: "010-4584-2116" },
  { code: "RAF6794", brand: "RAFIQ cosmetics", segment: "skincare", gubun: "", email: "", contactEmail: "yjm@rafiqcosmetics.com", contactName: "윤정민", instagram: "", phone: "010-6691-3119" },
  { code: "RAI7801", brand: "RAINT (화장품·생활화학용품)", segment: "skincare", gubun: "", email: "", contactEmail: "plan06@raint.kr", contactName: "장지운", instagram: "", phone: "010-9236-9579" },
  { code: "RAP5629", brand: "(주)라파스", segment: "skincare", gubun: "", email: "sales@raphas.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "RAT2649", brand: "(주)알에이치앤비브랜즈", segment: "skincare", gubun: "스킨케어", email: "info@rhnb.co.kr", contactEmail: "", contactName: "", instagram: "@pretty_actually", phone: "" },
  { code: "RAV9985", brand: "파인월드 / 라비엘", segment: "skincare", gubun: "스킨케어", email: "sales@raviel.co.kr", contactEmail: "", contactName: "", instagram: "@raviel.official", phone: "" },
  { code: "RAW5367", brand: "RAWGA", segment: "skincare", gubun: "", email: "", contactEmail: "john@rawga.com", contactName: "김형석", instagram: "", phone: "010-7588-8116" },
  { code: "RBK4652", brand: "주식회사 일레븐코퍼레이션", segment: "skincare", gubun: "헤어", email: "b2b@11corp.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "REB1308", brand: "리봄화장품", segment: "skincare", gubun: "", email: "overseas@rebom.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "REB4797", brand: "RED BIO COMPANY", segment: "skincare", gubun: "", email: "", contactEmail: "anhhong@redbiocp.com", contactName: "홍안민", instagram: "", phone: "010-8014-6071" },
  { code: "RED9716", brand: "주식회사 레드바이오컴퍼니", segment: "skincare", gubun: "", email: "info@redbiocp.com", contactEmail: "woong@redbiocp.com", contactName: "정연웅", instagram: "", phone: "010-4070-2389" },
  { code: "REJ5441", brand: "리쥬멜라 코리아", segment: "skincare", gubun: "더마", email: "rejumela@naver.com", contactEmail: "rejumela@naver.com", contactName: "김경환", instagram: "", phone: "010-4552-0133" },
  { code: "RGX6769", brand: "로가", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "RIB2433", brand: "RING THE BELL", segment: "skincare", gubun: "", email: "", contactEmail: "airliftkim@ringthebell.kr", contactName: "김종철", instagram: "", phone: "010-3344-6541" },
  { code: "RIN6145", brand: "주식회사 링더벨", segment: "skincare", gubun: "더마", email: "info@ringthebell.kr", contactEmail: "", contactName: "", instagram: "@resear_korea", phone: "" },
  { code: "ROK4804", brand: "(주) 록키스", segment: "skincare", gubun: "스킨케어", email: "redgirl8282@daum.net", contactEmail: "", contactName: "", instagram: "@rokkiss_official", phone: "" },
  { code: "ROK9047", brand: "ROK (Daha)", segment: "skincare", gubun: "", email: "", contactEmail: "yerin_cho@rokcorp.co.kr / global_sales@rokcorp.co.kr", contactName: "조예린", instagram: "", phone: "010-4772-0875" },
  { code: "RUT4446", brand: "LK company", segment: "skincare", gubun: "바디", email: "rutiin7@naver.com", contactEmail: "rutiin7@naver.com", contactName: "원선아", instagram: "", phone: "010-9303-6255" },
  { code: "SAC4914", brand: "SACCIBIO", segment: "skincare", gubun: "", email: "", contactEmail: "jhchoi@saccibio.com", contactName: "최재혁", instagram: "", phone: "010-2112-9273" },
  { code: "SAE2013", brand: "(주)새로핸즈", segment: "skincare", gubun: "향수", email: "saero@saero.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SAL1421", brand: "솔테라피", segment: "skincare", gubun: "바디", email: "info@saltherapy.biz", contactEmail: "", contactName: "", instagram: "@saltherapy.official", phone: "" },
  { code: "SAM5493", brand: "SAMJUNG / 삼정", segment: "skincare", gubun: "", email: "", contactEmail: "jmjung@e-samjung.co.kr", contactName: "정재민", instagram: "", phone: "010-4532-3697" },
  { code: "SAN5753", brand: "㈜상떼화장품", segment: "skincare", gubun: "더마", email: "sante@santecosmetic.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SCE8285", brand: "센티카", segment: "skincare", gubun: "향수", email: "scentica@raint.kr", contactEmail: "", contactName: "", instagram: "@scentica_official", phone: "" },
  { code: "SEA4669", brand: "(주)섬섬바이오", segment: "skincare", gubun: "스킨케어", email: "sumsum2022@naver.com", contactEmail: "", contactName: "", instagram: "@searce_official", phone: "" },
  { code: "SEO9008", brand: "서울화장품", segment: "skincare", gubun: "", email: "sarah.k@seoulcos.co.kr", contactEmail: "kimjy@seoulcos.co.kr", contactName: "김정영", instagram: "", phone: "010·4704·9499" },
  { code: "SER7292", brand: "(주)세리화장품", segment: "skincare", gubun: "", email: "", contactEmail: "must@sericos.co.kr", contactName: "신제욱", instagram: "", phone: "010-5803-2619" },
  { code: "SEU1849", brand: "Seunggun Cosmetics / LOOBEE / SGCOSMETICS", segment: "skincare", gubun: "", email: "", contactEmail: "loobeecms@naver.com", contactName: "LEE SOO HYANG", instagram: "", phone: "010-5958-7882" },
  { code: "SFB1880", brand: "SHAANXI FAIRIR BIOTECH CO.,LTD", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SGJ2460", brand: "주식회사 사계절", segment: "skincare", gubun: "이너뷰티", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SHI1094", brand: "Shionle / (주)신안코스메틱", segment: "skincare", gubun: "", email: "", contactEmail: "shionle1004@naver.com", contactName: "박동원", instagram: "", phone: "010-6755-1798" },
  { code: "SHI2028", brand: "SHINAN COSMETICS Co., Ltd.", segment: "skincare", gubun: "스킨케어", email: "admin@shinancosmetics.co.kr", contactEmail: "", contactName: "", instagram: "@shionle", phone: "" },
  { code: "SHI2171", brand: "SHAAN HONQ INT'L COSMETICS CORP.", segment: "skincare", gubun: "헤어", email: "sophia@shaanhonq.com.tw", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SIL1585", brand: "실리스카(주)", segment: "skincare", gubun: "", email: "info@silisca.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SIM8877", brand: "심플레", segment: "skincare", gubun: "스킨케어", email: "ina@liebemi.com", contactEmail: "ina@liebemi.com", contactName: "조인아", instagram: "@simplete_official", phone: "0)10-7750-4536" },
  { code: "SKI2315", brand: "SKINISGOOD", segment: "skincare", gubun: "더마", email: "yklee@skinisgood.com", contactEmail: "lej@skinisgood.com", contactName: "이은지", instagram: "@lissederm_official", phone: "010-8653-8271" },
  { code: "SKI3054", brand: "SKINNPLUS CO.,LTD", segment: "skincare", gubun: "", email: "skinnplus@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SKI6859", brand: "(주)스킨앤플러스 (Skin&Plus) / SP", segment: "skincare", gubun: "", email: "", contactEmail: "skinn2012@naver.com", contactName: "김종환", instagram: "", phone: "010-3856-4392" },
  { code: "SKI8337", brand: "(주)스킨솔루션", segment: "skincare", gubun: "", email: "naluke@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SKS5499", brand: "SKIN SOLUTION", segment: "skincare", gubun: "", email: "", contactEmail: "ymsong@skinsolution.co.kr", contactName: "송유미", instagram: "", phone: "010-4050-3686" },
  { code: "SME7648", brand: "(주)에스엠에코랩", segment: "skincare", gubun: "", email: "smecolab@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SNO2263", brand: "SNOWBLING (스노우블링)", segment: "skincare", gubun: "", email: "", contactEmail: "snowbling88@gmail.com", contactName: "김평천", instagram: "", phone: "010-2340-6584" },
  { code: "SOL7813", brand: "(주)코비스타", segment: "skincare", gubun: "헤어", email: "kbeauty@kobizstar.com", contactEmail: "hilee@kobizstar.com", contactName: "이혜인", instagram: "@solep_scalp", phone: "010-2862-6445" },
  { code: "SOM2137", brand: "주식회사 텍스코", segment: "skincare", gubun: "바디", email: "somsajang@texkor.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SOM7449", brand: "SOMEWANG (NINGBO SOMEWANG PACKAGING)", segment: "skincare", gubun: "", email: "", contactEmail: "sales@somewang.com", contactName: "Tony SHEN", instagram: "", phone: "0086-13967811517-(WhatsApp / WeChat)" },
  { code: "SRX8361", brand: "(주)아이오쓰리", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "STA3004", brand: "StarLuxe (주)스타럭스", segment: "skincare", gubun: "", email: "", contactEmail: "hlkim@starluxe.co.kr", contactName: "김호림", instagram: "", phone: "010-4511-1825" },
  { code: "STA6417", brand: "(주)케이피티", segment: "skincare", gubun: "", email: "mhs@starpheres.com", contactEmail: "jiangyanfu20@starpheres.com", contactName: "강단희", instagram: "", phone: "010-3291-3888" },
  { code: "STB5119", brand: "STB INTERNATIONAL (Simple is The Best)", segment: "skincare", gubun: "", email: "", contactEmail: "mkt02@stbint.co.kr", contactName: "", instagram: "", phone: "" },
  { code: "STU4481", brand: "studiodibs", segment: "skincare", gubun: "", email: "", contactEmail: "info@studiodibs.com", contactName: "황지홍", instagram: "@studiodibs", phone: "010-5575-3665" },
  { code: "STU8963", brand: "스튜디오17", segment: "beauty", gubun: "메이크업", email: "lrkim@thebkor.com", contactEmail: "", contactName: "", instagram: "@studio17_official", phone: "" },
  { code: "STU9369", brand: "스턴메디칼", segment: "skincare", gubun: "", email: "bjpark@mediforet.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SUP7793", brand: "(주)참존엔씨원", segment: "skincare", gubun: "스킨케어", email: "superbjhj@gmail.com", contactEmail: "superbjhj@gmail.com", contactName: "정현재", instagram: "@labonita_korea", phone: "010-9286-9318" },
  { code: "SYM4583", brand: "Symphony Cosmetic Inc.", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SYS6060", brand: "system4u ((주)시스템포유); S4u BEAUTY SYSTEM", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "박수정", instagram: "", phone: "010-3043-4524" },
  { code: "TAM5853", brand: "(주)비앤케이", segment: "skincare", gubun: "스킨케어", email: "contact@koreahnb.com", contactEmail: "", contactName: "", instagram: "@tambeautyme", phone: "" },
  { code: "TAP3690", brand: "TALENTS PACKING INTERNATIONAL LTD (TPI)", segment: "skincare", gubun: "", email: "", contactEmail: "sales5@talentsgroup.com.cn / peter@talentsgroup.com.cn", contactName: "Vina Cheng", instagram: "", phone: "+86 13826571095" },
  { code: "TEN2469", brand: "일공일공 이미지플러스", segment: "skincare", gubun: "바디/이너뷰티", email: "1010master@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "THE1979", brand: "TAIZHOU HUADI ELECTRIC CO.,LTD", segment: "skincare", gubun: "", email: "info@huadicn.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "THE3473", brand: "THESERA", segment: "skincare", gubun: "", email: "mrinno@mrinno.com", contactEmail: "csh7722@mrinno.com", contactName: "최성희", instagram: "", phone: "010-8257-6630" },
  { code: "THE3552", brand: "주식회사 더연", segment: "skincare", gubun: "스킨케어", email: "theyeonsales@theyeon.net", contactEmail: "", contactName: "", instagram: "@theyeon_official", phone: "" },
  { code: "THE5708", brand: "THEBKOR (더비코리아)", segment: "skincare", gubun: "", email: "", contactEmail: "nskim@thebkor.com", contactName: "Nam Soo Kim", instagram: "", phone: "010-5224-1604" },
  { code: "THE6617", brand: "바루쟈", segment: "skincare", gubun: "스킨케어", email: "nsl@thevaruza.com", contactEmail: "", contactName: "", instagram: "@varuza_official", phone: "" },
  { code: "THE6716", brand: "(주)더엘그룹", segment: "skincare", gubun: "스킨케어", email: "marketing.theel@gmail.com", contactEmail: "marketing.theel@gmail.com", contactName: "김성윤", instagram: "@jacknrnl", phone: "010-9916-2678" },
  { code: "THE9481", brand: "더마퀸", segment: "skincare", gubun: "홈디바이스", email: "limta11@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "TOL4048", brand: "TOLY / Toly Korea, Inc. (Passionate About Packaging)", segment: "skincare", gubun: "", email: "", contactEmail: "ek@tolykorea.com", contactName: "권환준", instagram: "", phone: "010-8938-6530" },
  { code: "TOL7601", brand: "(주)톨리코리아", segment: "skincare", gubun: "", email: "", contactEmail: "sales@toly.kr", contactName: "김선웅", instagram: "", phone: "010-2733-5796" },
  { code: "TOM5960", brand: "주식회사 제트글로벌", segment: "skincare", gubun: "더마", email: "tomtittot.official@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "TOO4040", brand: "(주)한국쉬즈라인", segment: "skincare", gubun: "스킨케어/바디", email: "info@koreashesline.co.kr", contactEmail: "", contactName: "", instagram: "@toolif.official", phone: "" },
  { code: "TOU1441", brand: "터치인솔", segment: "beauty", gubun: "메이크업", email: "br@bonne.co.kr", contactEmail: "", contactName: "", instagram: "@touchinsol.official", phone: "" },
  { code: "TRE2941", brand: "TREEANNSEA 트리앤씨", segment: "skincare", gubun: "스킨케어", email: "global@treeannsea.co.kr", contactEmail: "info@treeannsea.co.kr", contactName: "Eunjung Kim", instagram: "@treeannsea_official", phone: "010-2422-5179" },
  { code: "TRE8645", brand: "Trendyproducts Co.,Ltd.", segment: "skincare", gubun: "", email: "info@trendyproducts.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "TRI9531", brand: "TRINICELL", segment: "skincare", gubun: "더마", email: "contact@trinicell.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "010-3614-7888" },
  { code: "TRO8008", brand: "TROIAREUKE", segment: "skincare", gubun: "더마", email: "stella@sislab.com", contactEmail: "", contactName: "", instagram: "@troiareuke_global", phone: "" },
  { code: "TRU7509", brand: "(주)유에스티", segment: "skincare", gubun: "스킨케어", email: "truthofbeauty@naver.com", contactEmail: "", contactName: "", instagram: "@truthofbeauty_official", phone: "" },
  { code: "TWO8960", brand: "TWOK INTERNATIONAL Co.,Ltd.", segment: "skincare", gubun: "네일", email: "info@twokinter.com", contactEmail: "", contactName: "", instagram: "@gelyours_global", phone: "" },
  { code: "ULF7509", brand: "(주)울파인", segment: "skincare", gubun: "홈디바이스", email: "ulfine@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "UNI3605", brand: "유니엔코리아", segment: "skincare", gubun: "", email: "info@unienkorea.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "UNS4276", brand: "브랜드", segment: "skincare", gubun: "", email: "", contactEmail: "dudxo397@naver.com", contactName: "김영태", instagram: "", phone: "010-8441-0759" },
  { code: "UNS7209", brand: "유니소재(주) (Uni-Solutions)", segment: "skincare", gubun: "", email: "", contactEmail: "kang3583@uni-solutions.co.kr", contactName: "강석영", instagram: "", phone: "010-9939-3583" },
  { code: "UZO5605", brand: "UZONE (Jiangyin Uzone International Trade Co.,Ltd / Jiangyin UZ Cosmetic Package Co.,Ltd)", segment: "skincare", gubun: "", email: "", contactEmail: "sales03@uzo-pak.com", contactName: "Emily Chen", instagram: "", phone: "0086-15000566421" },
  { code: "VAH5733", brand: "지비알아이디어", segment: "skincare", gubun: "스킨케어", email: "seo9009@hanmail.net", contactEmail: "", contactName: "", instagram: "@vah_korea", phone: "" },
  { code: "VAN7964", brand: "주식회사 반다비앤에이치", segment: "skincare", gubun: "스킨케어", email: "vandabnh@vanda.co.kr", contactEmail: "jhl1105@vanda.co.kr", contactName: "이주현", instagram: "@kiwiglow.official", phone: "010-7108-1912" },
  { code: "VAN8297", brand: "주식회사 정림에프앤에이치", segment: "skincare", gubun: "바디", email: "4674sjh@naver.com", contactEmail: "", contactName: "", instagram: "@vanava_cosmetics", phone: "" },
  { code: "VEL9208", brand: "VELYMONKEYS · THE BEAUTY PLAYGROUND / (주)블리몽키즈", segment: "skincare", gubun: "", email: "", contactEmail: "ben.choi@velymonkeys.com", contactName: "최인호", instagram: "", phone: "010-8446-5550" },
  { code: "VEN1772", brand: "(주)바이옵트", segment: "skincare", gubun: "더마", email: "info@venderma.com", contactEmail: "", contactName: "", instagram: "@venderma_official", phone: "" },
  { code: "VIE7189", brand: "VIEWTEL Co., Ltd.", segment: "skincare", gubun: "홈디바이스", email: "marketing@view-tel.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "VIN1078", brand: "VINACEUTICALS", segment: "skincare", gubun: "더마", email: "official@vinaceuticals.vn", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "WEL4320", brand: "주식회사 웰컴이엔앰", segment: "beauty", gubun: "메이크업", email: "dandymicn@welcomems.co.kr", contactEmail: "dandymicn@welcomems.co.kr", contactName: "김진만", instagram: "", phone: "010-7724-5733" },
  { code: "WFS3682", brand: "Wati For Skin", segment: "skincare", gubun: "스킨케어", email: "twotigers2222@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "WHA1557", brand: "와더스킨", segment: "skincare", gubun: "스킨케어", email: "whataskin7@gmail.com", contactEmail: "whataskin7@gmail.com", contactName: "Min Jong Seo", instagram: "", phone: "010-7759-4939" },
  { code: "WHA4084", brand: "(주)화인글로벌랩", segment: "skincare", gubun: "", email: "midilcos@gmail.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "WHO8836", brand: "후택", segment: "skincare", gubun: "", email: "biz@whotag.ai", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "WIZ2024", brand: "주식회사 위즈켐", segment: "skincare", gubun: "", email: "mjlee@wizchem.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "WOB8670", brand: "WONDER BATH (CSA COSMIC Co., Ltd.)", segment: "skincare", gubun: "스킨케어", email: "jsm@csacosmic.com", contactEmail: "", contactName: "", instagram: "@wonderbath_official", phone: "" },
  { code: "WOO3160", brand: "(주)우신화장품", segment: "skincare", gubun: "", email: "marketing@woosincos.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "WOO7974", brand: "WOOSUNG Cosmetic & Trading / (주)우성씨앤티", segment: "skincare", gubun: "", email: "", contactEmail: "suyeon@woosungcnt.co.kr / okwoosung@hanmail.net", contactName: "지수연", instagram: "", phone: "010-3327-2293" },
  { code: "XAT9689", brand: "세이션", segment: "skincare", gubun: "스킨케어", email: "overseas@xation.co.kr", contactEmail: "shawna@xation.co.kr / overseas@xation.co.kr", contactName: "양홍안", instagram: "", phone: "010-7502-6211" },
  { code: "XEL9253", brand: "와이에스메디", segment: "skincare", gubun: "", email: "beauty@ysmedi.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "XEN9264", brand: "(주)제노헬릭스", segment: "skincare", gubun: "더마", email: "xenohelix@xenohelix.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "YCE2645", brand: "(주)와이셀바이오메디칼", segment: "skincare", gubun: "", email: "info@ycellbio.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "YCE9526", brand: "ycellbio / Ycellbio Medical Co., Ltd. / (주)와이셀바이오메디컬", segment: "skincare", gubun: "", email: "", contactEmail: "black@ycellbio.com", contactName: "황인제", instagram: "", phone: "010-5602-8527" },
  { code: "YCF5388", brand: "유창에프씨 (주식회사 유창에프씨)", segment: "skincare", gubun: "", email: "", contactEmail: "sh.lee@ycfc.co.kr / sales3@ycfc.co.kr", contactName: "이성헌", instagram: "", phone: "010-9272-1476" },
  { code: "YDN4426", brand: "Yaxi Daily Necessities Co.,Ltd", segment: "skincare", gubun: "", email: "118183863@qq.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "YMT3577", brand: "YOULIAN MAKEUP TOOL (욜리브러쉬) / JBT International", segment: "skincare", gubun: "", email: "", contactEmail: "jbtinternational@naver.com", contactName: "김애론", instagram: "", phone: "010-2229-9912" },
  { code: "YNM8423", brand: "Y.N.M", segment: "beauty", gubun: "메이크업", email: "ynm@ynmcosmetic.co.kr", contactEmail: "", contactName: "", instagram: "@ynmbeauty_official", phone: "" },
  { code: "YOL6680", brand: "욜리 메이크업툴", segment: "skincare", gubun: "", email: "nicholas@yolybrush.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "YOU3872", brand: "(주)에스엠지유럽", segment: "skincare", gubun: "", email: "info@smgkorea.or.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "YOU4521", brand: "헤트라스", segment: "skincare", gubun: "향수", email: "globalsales@hetras.co.kr", contactEmail: "", contactName: "", instagram: "@hetras.official", phone: "" },
  { code: "YOU5341", brand: "레보아미", segment: "skincare", gubun: "스킨케어", email: "sun2268@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "YSM1285", brand: "Ys medi (YSMEDI Co.,Ltd)", segment: "skincare", gubun: "", email: "", contactEmail: "tania@ysmedi.kr", contactName: "Tania, Pan", instagram: "", phone: "+82. 10. 8894. 2861" },
  { code: "YUH2084", brand: "유한코스메틱", segment: "skincare", gubun: "", email: "dh.son@yuhancosmetics.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "YUH9170", brand: "유한양행 (Yuhan)", segment: "skincare", gubun: "", email: "", contactEmail: "ksm0084@yuhan.co.kr", contactName: "김상미", instagram: "", phone: "010-3085-9050" },
  { code: "ZCN2946", brand: "ZHEJIANG CHENYANG NONWOVEN CO., LTD", segment: "skincare", gubun: "", email: "", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "ZLB4075", brand: "ZL Bio (지엘바이오)", segment: "skincare", gubun: "", email: "", contactEmail: "sales@zlbio.com", contactName: "이주은", instagram: "", phone: "010-5804-6211" },
  { code: "ZOB1985", brand: "ZOE BIO (주)조에바이오", segment: "skincare", gubun: "", email: "", contactEmail: "romina@zoebio.co.kr", contactName: "조자은", instagram: "", phone: "010-6697-6812" },
];
