// AUTO-GENERATED — scripts/generate-companies.mjs 로 마스터시트에서 생성.
// 손으로 고치지 말 것. 총 270건 · beauty 36 · skincare 234 · 이메일 270.
//
// ⚠️ 연락처(email 등)는 서버 데이터다. 이 파일은 서버에서만 import되며(lib/codes.ts),
//    개인화 페이지(클라이언트)로는 code/brand/segment/gubun 만 넘긴다.

export interface Company {
  code: string;
  brand: string;
  segment: "beauty" | "skincare";
  gubun: string;
  email?: string;
  contactEmail?: string;
  contactName?: string;
  instagram?: string;
  phone?: string;
}

export const COMPANIES: Company[] = [
  { code: "AGE8187", brand: "Age20's", segment: "beauty", gubun: "색조", email: "privacy@aekyung.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/age20s_official", phone: "" },
  { code: "AHC4140", brand: "AHC", segment: "skincare", gubun: "스킨케어", email: "yuna.so@carverkorea.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ahc.official", phone: "" },
  { code: "AHR3907", brand: "아로 (AHRO)", segment: "skincare", gubun: "향수", email: "ahro_office@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ahro_official", phone: "" },
  { code: "AMU4288", brand: "어뮤즈", segment: "beauty", gubun: "색조", email: "help_amuse@amusemakeup.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/amuse", phone: "" },
  { code: "ANA7821", brand: "어네이즈 (ANAZE)", segment: "skincare", gubun: "헤어바디", email: "anaze1@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/anaze_official", phone: "" },
  { code: "ANA9720", brand: "아름다운나라화장품", segment: "skincare", gubun: "스킨케어", email: "webmaster@anaclimall.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/anaclimall", phone: "" },
  { code: "ARO5255", brand: "에이로마플라붐", segment: "skincare", gubun: "향수", email: "info@aromaflavum.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/aromaflavum.official", phone: "" },
  { code: "ARO7932", brand: "아로마티카", segment: "skincare", gubun: "스킨케어", email: "communication@aromatica.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/aromatica.life", phone: "" },
  { code: "ATI7638", brand: "에티에르", segment: "skincare", gubun: "향수", email: "bh@bravegirls.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/atiaer_official", phone: "" },
  { code: "ATS6784", brand: "ATS", segment: "skincare", gubun: "스킨케어", email: "webmaster@create.co.kr", contactEmail: "", contactName: "", instagram: "@ats_hair", phone: "" },
  { code: "AZH2100", brand: "AZH", segment: "skincare", gubun: "스킨케어", email: "info@interohrigin.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/azh_korea", phone: "" },
  { code: "BAL5732", brand: "볼빅", segment: "skincare", gubun: "헤어바디", email: "info@innogene.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ballvic_korea", phone: "" },
  { code: "BAN5149", brand: "바닐라코", segment: "skincare", gubun: "스킨케어", email: "banila@banila.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/banila_co", phone: "" },
  { code: "BAS9830", brand: "닥터베이스 (DR.BASE)", segment: "skincare", gubun: "스킨케어", email: "businesstroyh@drbase.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dr.base_official", phone: "" },
  { code: "BBI5934", brand: "삐아", segment: "beauty", gubun: "색조", email: "trde12027@bbia.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/bbia.official", phone: "" },
  { code: "BEA2451", brand: "조선미녀", segment: "skincare", gubun: "스킨케어", email: "support_kr@beautyofjoseon.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/beautyofjoseon_official", phone: "" },
  { code: "BEA4077", brand: "뷰디아니", segment: "skincare", gubun: "스킨케어", email: "hello@beaudiani.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/beaudiani", phone: "" },
  { code: "BEA6533", brand: "뷰앤디", segment: "skincare", gubun: "스킨케어", email: "marketing@globient.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/beaund_korea", phone: "" },
  { code: "BEA9898", brand: "뷰애드", segment: "skincare", gubun: "스킨케어", email: "beauadd@beauadd.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/beauadd.beauty", phone: "" },
  { code: "BER1156", brand: "베르가모", segment: "skincare", gubun: "스킨케어", email: "jy.kim@lkcos.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/bergamo_lk", phone: "" },
  { code: "BHA3062", brand: "비햅", segment: "skincare", gubun: "스킨케어", email: "hello@bhab.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/bhab_official", phone: "" },
  { code: "BIB4962", brand: "비비앙 (BIBIANG)", segment: "skincare", gubun: "향수", email: "official@bibiang.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/bibiang_official", phone: "" },
  { code: "BLA9756", brand: "블랑나뚜르", segment: "skincare", gubun: "스킨케어", email: "business@blancnature.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/blancnature_official", phone: "" },
  { code: "BOM7098", brand: "BOM", segment: "beauty", gubun: "색조", email: "bom_official@bstarlit.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/bomcosmetics_official", phone: "" },
  { code: "BON7248", brand: "본느", segment: "skincare", gubun: "스킨케어", email: "bonne2@bonne.co.kr", contactEmail: "", contactName: "", instagram: "@bonne_official", phone: "" },
  { code: "BON8197", brand: "본다이시크 (Bondichic)", segment: "skincare", gubun: "스킨케어", email: "kim@bondichic.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/bondichic_kr", phone: "" },
  { code: "BOR8303", brand: "본투스탠드아웃", segment: "skincare", gubun: "향수", email: "btso@housebylim.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/borntostandout.official", phone: "" },
  { code: "BOU8922", brand: "부케가르니", segment: "skincare", gubun: "헤어바디", email: "breatheb_sales_kr@grunamu.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/bouquetgarni_official", phone: "" },
  { code: "BRA4088", brand: "지쿱", segment: "skincare", gubun: "이너뷰티", email: "master@generalbio.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/gcoop_korea_official", phone: "" },
  { code: "BYP5994", brand: "바이플레이", segment: "beauty", gubun: "색조", email: "byplay@byplay.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/byplay_official", phone: "" },
  { code: "CAD5581", brand: "카디뷰", segment: "skincare", gubun: "헤어바디", email: "online@rbh.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/cadiveu_korea", phone: "" },
  { code: "CAR2307", brand: "케어놀로지 (Carenology)", segment: "skincare", gubun: "스킨케어", email: "official@carenology95.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/carenology_official", phone: "" },
  { code: "CAR4263", brand: "MJ Care", segment: "skincare", gubun: "스킨케어", email: "mijin_kor@mjcare.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/mijincosmetics_official", phone: "" },
  { code: "CEL1722", brand: "셀리맥스", segment: "skincare", gubun: "스킨케어", email: "contact@celimax.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/celimax_official", phone: "" },
  { code: "CEL3559", brand: "셀로라", segment: "skincare", gubun: "스킨케어", email: "business@celoraby.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/celoraby_official", phone: "" },
  { code: "CHA1060", brand: "참존", segment: "skincare", gubun: "스킨케어", email: "online@charmzone.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/charmzone.official", phone: "" },
  { code: "CHA3115", brand: "샤르드", segment: "skincare", gubun: "스킨케어", email: "global@newselect.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/charde_official", phone: "" },
  { code: "CHA4765", brand: "샬랑드파리", segment: "skincare", gubun: "향수", email: "jc@opusasia.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/challansdeparis_global", phone: "" },
  { code: "CHO3497", brand: "츄니", segment: "beauty", gubun: "색조", email: "choonee@ikdno.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/choonee_", phone: "" },
  { code: "CIV3744", brand: "시바산", segment: "skincare", gubun: "스킨케어", email: "info@civasan.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/civasan.official", phone: "" },
  { code: "CLE6047", brand: "끌레드벨", segment: "beauty", gubun: "색조", email: "cledbel@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/cledbel_official", phone: "" },
  { code: "CLI9854", brand: "CLIO", segment: "beauty", gubun: "색조", email: "clioir@clio.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/clio_official", phone: "" },
  { code: "COM7732", brand: "콤마나인", segment: "beauty", gubun: "색조", email: "official@jsnlab.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/comma_nine", phone: "" },
  { code: "COR4525", brand: "코랄헤이즈 (Coralhaze)", segment: "beauty", gubun: "색조", email: "zoo8@inscobee.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/coralhaze_beauty", phone: "" },
  { code: "COR5374", brand: "코리아나", segment: "skincare", gubun: "스킨케어", email: "gomerim@coreana.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/coreanacosmetics", phone: "" },
  { code: "COS5673", brand: "액티브레이어", segment: "skincare", gubun: "스킨케어", email: "cosmoreplus@cosmoreplus.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/activlayr", phone: "" },
  { code: "COS6622", brand: "VT코스메틱", segment: "skincare", gubun: "스킨케어", email: "sales@vt-cosmetics.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/vtcosmetics_official", phone: "" },
  { code: "COS8190", brand: "리들샷", segment: "skincare", gubun: "스킨케어", email: "enc@enccosmetic.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/vtcosmetics_official", phone: "" },
  { code: "CPD6467", brand: "투에이엔", segment: "beauty", gubun: "색조", email: "2an@ianfnc.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/2an_official", phone: "" },
  { code: "CUR3215", brand: "커리쉴", segment: "skincare", gubun: "헤어바디", email: "curlyshyll@continuumpe.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/curlyshyll_official", phone: "" },
  { code: "CUS6789", brand: "씨유스킨", segment: "skincare", gubun: "스킨케어", email: "301927@cuskin.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/cuskin_official", phone: "" },
  { code: "DAL1638", brand: "달바", segment: "skincare", gubun: "스킨케어", email: "biz_korea@dalba.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dalba_global", phone: "" },
  { code: "DAS4330", brand: "데이지크", segment: "beauty", gubun: "색조", email: "marketing@dasique.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dasique_official", phone: "" },
  { code: "DDI1338", brand: "에이딕트 (A'ddict)", segment: "skincare", gubun: "향수", email: "a-ddict@a-ddict.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/addctfragrances", phone: "" },
  { code: "DEA8401", brand: "디어달리아", segment: "beauty", gubun: "색조", email: "support@deardahlia.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/deardahlia_beauty", phone: "" },
  { code: "DEM3345", brand: "디마르3", segment: "skincare", gubun: "스킨케어", email: "b2b@demar3.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/demar3_official", phone: "" },
  { code: "DEM7913", brand: "디마프", segment: "skincare", gubun: "스킨케어", email: "contact@demaf.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/demaf.official", phone: "" },
  { code: "DER8086", brand: "더마펌", segment: "skincare", gubun: "스킨케어", email: "cs@dermafirm.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dermafirm_kr", phone: "" },
  { code: "DEW8370", brand: "듀이셀", segment: "skincare", gubun: "스킨케어", email: "business@buddynetworks.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dewycel_korea", phone: "" },
  { code: "DIA4910", brand: "다이아린", segment: "skincare", gubun: "스킨케어", email: "drcos1@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/diarin_official", phone: "" },
  { code: "DIF8477", brand: "디퍼앤디퍼 (Differ&Deeper)", segment: "skincare", gubun: "스킨케어", email: "differndeeper@themomentgroup.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/differndeeper_official", phone: "" },
  { code: "DOC5268", brand: "닥터바이오", segment: "skincare", gubun: "헤어바디", email: "sales@rokcorp.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dr.bio_official", phone: "" },
  { code: "DON9842", brand: "동구밭", segment: "skincare", gubun: "헤어바디", email: "collaboration@donggubat.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/donggubat_story", phone: "" },
  { code: "DOO9943", brand: "댕기머리", segment: "skincare", gubun: "헤어바디", email: "envy4101@dooricare.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/daenggimeori_kr", phone: "" },
  { code: "DPC9624", brand: "DPC", segment: "skincare", gubun: "스킨케어", email: "yacoche@makeastosay.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dpc_korea_official", phone: "" },
  { code: "DPP2164", brand: "디퍼 (DPPR)", segment: "skincare", gubun: "스킨케어", email: "contact@dpprskin.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dppr_official", phone: "" },
  { code: "DRD1335", brand: "닥터디퍼런트", segment: "skincare", gubun: "스킨케어", email: "snb@drdifferent.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/drdifferent_official", phone: "" },
  { code: "DRE4316", brand: "W.DRESSROOM", segment: "skincare", gubun: "향수", email: "repinade@trend-i.net", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/w.dressroom", phone: "" },
  { code: "DRF7504", brand: "닥터포헤어", segment: "skincare", gubun: "헤어바디", email: "global_mkt@wyattcorp.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/drforhair.kr", phone: "" },
  { code: "DRG9067", brand: "닥터그라프트", segment: "skincare", gubun: "헤어바디", email: "drgraft@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/drgraft_official", phone: "" },
  { code: "DRH1767", brand: "닥터하스킨", segment: "skincare", gubun: "스킨케어", email: "tech@drhaskin.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/drhaskin_official", phone: "" },
  { code: "DRJ1514", brand: "닥터자르트", segment: "skincare", gubun: "스킨케어", email: "webmaster@drjart.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/drjart", phone: "" },
  { code: "DUF4780", brand: "DUFT&DOFT", segment: "skincare", gubun: "헤어바디", email: "cp@dreamcos.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/duftndoft", phone: "" },
  { code: "EBB6710", brand: "EBBM", segment: "skincare", gubun: "스킨케어", email: "ebbmkorea@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/beauty_ebbm", phone: "" },
  { code: "ECL5172", brand: "에끌라두", segment: "skincare", gubun: "스킨케어", email: "service@ecladoplus.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/eclado__official", phone: "" },
  { code: "ELI3893", brand: "엘리메르", segment: "skincare", gubun: "스킨케어", email: "ryeohk@beautyairport.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/elimere.official", phone: "" },
  { code: "ENF2486", brand: "앙포레", segment: "skincare", gubun: "스킨케어", email: "main@enforetenf.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/enforet_official", phone: "" },
  { code: "ENP8201", brand: "엔프라니", segment: "skincare", gubun: "스킨케어", email: "sn.cho@enprani.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/enprani_official", phone: "" },
  { code: "ENT2565", brand: "엔트로피 메이크업 (ENTROPY Makeup)", segment: "beauty", gubun: "색조", email: "info@entropymakeup.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/entropymakeup", phone: "" },
  { code: "ENT4452", brand: "ENTH", segment: "beauty", gubun: "색조", email: "enthsales@enth.co.kr", contactEmail: "", contactName: "", instagram: "@enth_official", phone: "" },
  { code: "ENT8183", brand: "엔트로피 메이크업", segment: "beauty", gubun: "색조", email: "info@entropymakeup.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/entropymakeup", phone: "" },
  { code: "EYE3789", brand: "아이젤", segment: "skincare", gubun: "스킨케어", email: "eyesel01@naver.com", contactEmail: "", contactName: "", instagram: "@izelofficial", phone: "" },
  { code: "FAR1150", brand: "파머스초이스", segment: "skincare", gubun: "스킨케어", email: "fgk-1@hanmail.net", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/farmerscos", phone: "" },
  { code: "FEM1854", brand: "파뮤", segment: "skincare", gubun: "스킨케어", email: "online@femmue.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/femmue_korea", phone: "" },
  { code: "FOR3957", brand: "포뮬리에 (Formulier)", segment: "skincare", gubun: "스킨케어", email: "cpcosmetic@cpcosmetic.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/formulier_cosmetic", phone: "" },
  { code: "FOR6383", brand: "포렌코즈", segment: "skincare", gubun: "스킨케어", email: "jwlee@forencos.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/forencos_official", phone: "" },
  { code: "FRA4263", brand: "프라포투투 (FRA422)", segment: "skincare", gubun: "향수", email: "contact@fra422.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/fra422.official", phone: "" },
  { code: "FRO3741", brand: "프롬리에", segment: "skincare", gubun: "스킨케어", email: "business@fromrier.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/fromrier.official", phone: "" },
  { code: "FRU3087", brand: "프루디아", segment: "skincare", gubun: "스킨케어", email: "frudia@welcos.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/frudia.official", phone: "" },
  { code: "FUL2397", brand: "풀림", segment: "skincare", gubun: "스킨케어", email: "fulim@fulim.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/fulim_official", phone: "" },
  { code: "FUL5600", brand: "풀리 (FULLY)", segment: "skincare", gubun: "스킨케어", email: "cs@adaptkorea.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/fully___official", phone: "" },
  { code: "GEN1760", brand: "제나벨", segment: "skincare", gubun: "스킨케어", email: "contact@genalab.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/genabelle_official", phone: "" },
  { code: "GET1200", brand: "라엘", segment: "skincare", gubun: "스킨케어", email: "raelkorea@getrael.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/get_rael", phone: "" },
  { code: "GIK8164", brand: "GIK", segment: "skincare", gubun: "향수", email: "trade@gikcos.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/gik.korea", phone: "" },
  { code: "GIV6609", brand: "지베르니", segment: "skincare", gubun: "스킨케어", email: "giverny_mkt@bnhcosmetics.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/giverny_korea", phone: "" },
  { code: "GLO8836", brand: "글로이스트", segment: "skincare", gubun: "스킨케어", email: "glowiest@sophiecompany.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/glowiest.official", phone: "" },
  { code: "GLY7975", brand: "글맆 (GLYF)", segment: "beauty", gubun: "색조", email: "help@beaubble.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/glyfing", phone: "" },
  { code: "GRE5078", brand: "그렛테", segment: "skincare", gubun: "헤어바디", email: "clsrna3@naver.com", contactEmail: "", contactName: "", instagram: "@grette_official", phone: "" },
  { code: "GRO1733", brand: "그루밍랩", segment: "skincare", gubun: "헤어바디", email: "mr5@mr5shop.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/groominglab.official", phone: "" },
  { code: "HAI7802", brand: "헤어플러스", segment: "skincare", gubun: "헤어바디", email: "marketing@hairplus.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/hairplus.official", phone: "" },
  { code: "HAL3879", brand: "헤일앤데일", segment: "skincare", gubun: "스킨케어", email: "khk@aqualex.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/haleanddale.official", phone: "" },
  { code: "HAN9206", brand: "한스킨", segment: "skincare", gubun: "스킨케어", email: "webmaster@celltrionskincure.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/hanskin_global", phone: "" },
  { code: "HAR4838", brand: "하루하루원더", segment: "skincare", gubun: "스킨케어", email: "cs@thedfs.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/haruharuwonder_official", phone: "" },
  { code: "HAR9574", brand: "하루뷰티", segment: "skincare", gubun: "스킨케어", email: "romanalady@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "HEA7691", brand: "하트퍼센트 (Heart Percent)", segment: "beauty", gubun: "색조", email: "heartpercent2019@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/heartpercent", phone: "" },
  { code: "HEM2968", brand: "헤메코", segment: "skincare", gubun: "헤어바디", email: "content@hemeko.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/hemeko.o", phone: "" },
  { code: "HEV1268", brand: "헤브블루", segment: "skincare", gubun: "스킨케어", email: "contact@heveblue.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/heveblue_cosmetic", phone: "" },
  { code: "HIS5215", brand: "히스토랩", segment: "skincare", gubun: "스킨케어", email: "medians@histolab.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/histolab_official", phone: "" },
  { code: "HUX1168", brand: "헉슬리", segment: "skincare", gubun: "스킨케어", email: "mkt@nordmason.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/huxley_korea", phone: "" },
  { code: "HYE1496", brand: "혜자 (Hyeja)", segment: "skincare", gubun: "스킨케어", email: "info@hyejaskincare.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/hyejaskincare", phone: "" },
  { code: "IDE8016", brand: "이데넬", segment: "skincare", gubun: "스킨케어", email: "srjsy0801@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/idenel_official", phone: "" },
  { code: "ISO6451", brand: "아이소브", segment: "skincare", gubun: "스킨케어", email: "info@isov.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/isov__official", phone: "" },
  { code: "ITS7941", brand: "잇츠스킨", segment: "skincare", gubun: "스킨케어", email: "ircontact@itshanbul.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/itsskin_official", phone: "" },
  { code: "IUN1912", brand: "아이유닉", segment: "skincare", gubun: "스킨케어", email: "iunik@iunikcos.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/iunik_official", phone: "" },
  { code: "JAS8513", brand: "JAS", segment: "skincare", gubun: "스킨케어", email: "peoplenco@daum.net", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "JAY3328", brand: "제이준코스메틱", segment: "skincare", gubun: "스킨케어", email: "cs@jayjun.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/jayjuncos", phone: "" },
  { code: "JEJ2962", brand: "제주닮", segment: "skincare", gubun: "향수", email: "jejudarm@nate.com", contactEmail: "", contactName: "", instagram: "@jejudalm_official", phone: "" },
  { code: "JOY8245", brand: "죠이라이프", segment: "skincare", gubun: "스킨케어", email: "joylife@joylife.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/joylife.korea", phone: "" },
  { code: "JSR9719", brand: "제이스 레시피", segment: "skincare", gubun: "스킨케어", email: "jsrecipe.info@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/jsrecipe_official", phone: "" },
  { code: "JUM3465", brand: "주미소", segment: "skincare", gubun: "스킨케어", email: "jumiso_korea@jumiso.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/jumiso_official", phone: "" },
  { code: "JUN5897", brand: "정샘물", segment: "beauty", gubun: "색조", email: "jsmbeauty@jsmbeauty.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/jsmbeauty_", phone: "" },
  { code: "KDH1919", brand: "오샤르", segment: "skincare", gubun: "스킨케어", email: "koreacnb@koreacandb.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "KID8866", brand: "키덤스", segment: "skincare", gubun: "스킨케어", email: "kaddums@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/kiddums_official", phone: "" },
  { code: "KIR6235", brand: "키라니아", segment: "skincare", gubun: "헤어바디", email: "info@creativewith.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/kiraniaofficial", phone: "" },
  { code: "KNO8106", brand: "노크 (KNOCK)", segment: "skincare", gubun: "헤어바디", email: "sales@benow.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/knock_comma", phone: "" },
  { code: "KOC3243", brand: "코코스타", segment: "skincare", gubun: "스킨케어", email: "cs@kocostar.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/kocostar_korea", phone: "" },
  { code: "KOP4367", brand: "코페르", segment: "skincare", gubun: "스킨케어", email: "trend@bestinnovation.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/kopher_official", phone: "" },
  { code: "KUR1153", brand: "커브드 (Kurved)", segment: "skincare", gubun: "스킨케어", email: "official@kurved.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/kurved.kr", phone: "" },
  { code: "KVJ1796", brand: "프렌치파머시", segment: "skincare", gubun: "스킨케어", email: "sindopng@sindopng.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/frenchpharmerci_official", phone: "" },
  { code: "LAK4846", brand: "라카", segment: "beauty", gubun: "색조", email: "k-sales@laka.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/laka.official", phone: "" },
  { code: "LAN8461", brand: "라네뜨떼", segment: "skincare", gubun: "향수", email: "support@lanettete.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lanette__", phone: "" },
  { code: "LAS6166", brand: "라샘", segment: "skincare", gubun: "헤어바디", email: "lasaemcos@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lasaem", phone: "" },
  { code: "LBB9536", brand: "LBB", segment: "skincare", gubun: "스킨케어", email: "cs@lbbkorea.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lbb_cellbeauty", phone: "" },
  { code: "LEP7389", brand: "르플랑에떼", segment: "skincare", gubun: "향수", email: "hello@artnperfume.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lepleinete_official", phone: "" },
  { code: "LIF1169", brand: "LIFE 4.0", segment: "skincare", gubun: "스킨케어", email: "nh.park@aonebnh.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/life4.0_official", phone: "" },
  { code: "LIF1774", brand: "라이프넷", segment: "skincare", gubun: "헤어바디", email: "bjkim@mefactory.co.kr", contactEmail: "", contactName: "", instagram: "@lifenet_official", phone: "" },
  { code: "LIL7557", brand: "릴리이브 (LILYEVE)", segment: "skincare", gubun: "헤어바디", email: "contact@bitelab.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lilyeve.kr", phone: "" },
  { code: "LIZ2040", brand: "리즈케이", segment: "skincare", gubun: "스킨케어", email: "lizkmk@lizk-cosmetics.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lizk_official", phone: "" },
  { code: "LOC8139", brand: "락컬러", segment: "beauty", gubun: "색조", email: "k-cs@dkcos.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lockcolor.korea", phone: "" },
  { code: "LOE5285", brand: "로에", segment: "skincare", gubun: "향수", email: "sales@goodscentpeople.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/loe_cosmetics_official", phone: "" },
  { code: "LSE6037", brand: "엘씨드", segment: "skincare", gubun: "스킨케어", email: "lseed20@lseed-int.com", contactEmail: "", contactName: "", instagram: "@lseed_official", phone: "" },
  { code: "LUB6292", brand: "루비랩 (LUBYLAB)", segment: "skincare", gubun: "스킨케어", email: "lubylab@lubylab.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/lubylab_official", phone: "" },
  { code: "LUV8562", brand: "러붐", segment: "beauty", gubun: "색조", email: "yhp0111@luvum.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/luvum_official", phone: "" },
  { code: "MAL6037", brand: "말표", segment: "skincare", gubun: "스킨케어", email: "customer@malpyo.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/malpyo", phone: "" },
  { code: "MAN8096", brand: "마녀공장", segment: "skincare", gubun: "스킨케어", email: "manyofactory_cs@manyo.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/manyofactory_official", phone: "" },
  { code: "MAR4720", brand: "마르시끄", segment: "beauty", gubun: "색조", email: "business@marshique.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/marshique_official", phone: "" },
  { code: "MAS6845", brand: "마실", segment: "skincare", gubun: "헤어바디", email: "masil@bijukorea.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/masil_official_ko", phone: "" },
  { code: "MAT7608", brand: "MATRIGEN", segment: "skincare", gubun: "스킨케어", email: "cosmocnt20@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/matrigen_cosmetics", phone: "" },
  { code: "MAX1043", brand: "맥스클리닉", segment: "skincare", gubun: "스킨케어", email: "naturenbio@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/maxclinic", phone: "" },
  { code: "MED3080", brand: "메디필", segment: "skincare", gubun: "스킨케어", email: "skinidea@medipeel.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/medipeel_official", phone: "" },
  { code: "MED8118", brand: "메디힐", segment: "skincare", gubun: "스킨케어", email: "help@medihealcos.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/mediheal_official", phone: "" },
  { code: "MEL4748", brand: "멜릭서", segment: "skincare", gubun: "스킨케어", email: "info@melixir.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/melixirskincare", phone: "" },
  { code: "MEN6189", brand: "메노킨", segment: "skincare", gubun: "스킨케어", email: "sales@menokin.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/menokin_official", phone: "" },
  { code: "MID3521", brand: "미다 (MIDHA)", segment: "skincare", gubun: "스킨케어", email: "midha@midha.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/midha_official", phone: "" },
  { code: "MIL3486", brand: "밀리밀리", segment: "skincare", gubun: "헤어바디", email: "marketing@millius-corp.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/millimilli.official", phone: "" },
  { code: "MIN5775", brand: "민티드", segment: "skincare", gubun: "헤어바디", email: "mintedshop@unfoundism.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/minted.official", phone: "" },
  { code: "MIS7003", brand: "미샤", segment: "skincare", gubun: "스킨케어", email: "cs@ableshop.net", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/missha.official", phone: "" },
  { code: "MIX6983", brand: "믹순", segment: "skincare", gubun: "스킨케어", email: "b2binquiry@pkcosm.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/mixsoon_official", phone: "" },
  { code: "MOI4678", brand: "모이컬러", segment: "beauty", gubun: "색조", email: "moicolor@moicolor.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/moicolor_official", phone: "" },
  { code: "MON9775", brand: "몽디에스", segment: "skincare", gubun: "스킨케어", email: "admin@360per.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/mongdies_official", phone: "" },
  { code: "MOO8246", brand: "물다", segment: "beauty", gubun: "색조", email: "moolda-m@artfacekorea.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/moolda_official", phone: "" },
  { code: "MOR7015", brand: "모린", segment: "skincare", gubun: "스킨케어", email: "morin@imorin.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/morin.rim", phone: "" },
  { code: "MUD9021", brand: "뮤드", segment: "beauty", gubun: "색조", email: "mude_global@mude.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/mude_official", phone: "" },
  { code: "MUE2774", brand: "뮤에이", segment: "skincare", gubun: "스킨케어", email: "muei@dosados.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/muei.kr", phone: "" },
  { code: "MUM4550", brand: "멈칫", segment: "skincare", gubun: "향수", email: "wrms@mumchit.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/mumchit_", phone: "" },
  { code: "NAR3757", brand: "나르카 (NARKA)", segment: "skincare", gubun: "헤어바디", email: "contact@uncmhm.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/narka_you", phone: "" },
  { code: "NAR8189", brand: "나르카", segment: "skincare", gubun: "헤어바디", email: "global@uncmhm.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/narka_you", phone: "" },
  { code: "NAT6203", brand: "자연나라", segment: "skincare", gubun: "스킨케어", email: "csg0907@nature1770.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NAT7086", brand: "내추럴더마프로젝트", segment: "skincare", gubun: "스킨케어", email: "partner@naturaldermaproject.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/naturaldermaproject.official", phone: "" },
  { code: "NAT7723", brand: "네이처리퍼블릭", segment: "skincare", gubun: "스킨케어", email: "mkt@naturerepublic.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/naturerepublic_kr", phone: "" },
  { code: "NAV8499", brand: "나비클 (Navicle)", segment: "skincare", gubun: "스킨케어", email: "madc_01@madc.co.kr", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "NEO7977", brand: "네오젠", segment: "skincare", gubun: "스킨케어", email: "hello@outinco.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/neogen_official", phone: "" },
  { code: "NEO8412", brand: "아토팜", segment: "skincare", gubun: "스킨케어", email: "neoshop@neopharm.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/atopalm_official", phone: "" },
  { code: "NES5123", brand: "네쉬 (nesh)", segment: "skincare", gubun: "헤어바디", email: "qna@layerscosmetic.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/nesh.kr", phone: "" },
  { code: "NIN2386", brand: "나인밀라", segment: "skincare", gubun: "헤어바디", email: "ninemila@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ninemila.official", phone: "" },
  { code: "NON6799", brand: "논픽션", segment: "skincare", gubun: "향수", email: "hello@nonfiction.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/official.nonfiction", phone: "" },
  { code: "NOR4633", brand: "노디너리", segment: "skincare", gubun: "스킨케어", email: "contact@nordinary.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/nordinary_official", phone: "" },
  { code: "NUM6688", brand: "넘버즈인", segment: "skincare", gubun: "스킨케어", email: "marketing@benow.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/numbuzin_official", phone: "" },
  { code: "NUT4558", brand: "누텍스처 (NuTexture)", segment: "skincare", gubun: "스킨케어", email: "hello@nutexture.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/nutexture.official", phone: "" },
  { code: "OHO4424", brand: "오호라", segment: "beauty", gubun: "색조", email: "ohora_partnership@ohora.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ohora_official", phone: "" },
  { code: "OHS3299", brand: "오센트 (OHSCENT)", segment: "skincare", gubun: "향수", email: "hy@ohscent.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ohscent", phone: "" },
  { code: "OLI5248", brand: "올리크", segment: "skincare", gubun: "스킨케어", email: "inform@orlic.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/olikk", phone: "" },
  { code: "OLI9908", brand: "프롬더스킨", segment: "skincare", gubun: "스킨케어", email: "biomoa_@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/fromtheskin_official", phone: "" },
  { code: "ONE2388", brand: "원데이즈유", segment: "skincare", gubun: "스킨케어", email: "sales@oukorea.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/onedaysyou_official", phone: "" },
  { code: "ONE4154", brand: "원씽", segment: "skincare", gubun: "스킨케어", email: "onething@onething.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/onething_official", phone: "" },
  { code: "ONG7516", brand: "온그리디언츠", segment: "skincare", gubun: "스킨케어", email: "ceo@powerplayer.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ongredients.official", phone: "" },
  { code: "ORJ4622", brand: "오르제나", segment: "skincare", gubun: "스킨케어", email: "marketing@wannabecosmetic.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/orjena_official", phone: "" },
  { code: "PAP6358", brand: "파파레서피", segment: "skincare", gubun: "스킨케어", email: "paparecipe@costory.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/paparecipe_official", phone: "" },
  { code: "PAR9620", brand: "파넬", segment: "skincare", gubun: "스킨케어", email: "eleven@11corp.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/parnell.official", phone: "" },
  { code: "PES8878", brand: "페사드", segment: "skincare", gubun: "향수", email: "info@pesade.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/pesade_official", phone: "" },
  { code: "PHA1684", brand: "파메어스", segment: "skincare", gubun: "스킨케어", email: "pharmearth@pharmearth.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/pharmearthonline", phone: "" },
  { code: "PHY8919", brand: "피몽쉐", segment: "skincare", gubun: "스킨케어", email: "retail@edkspa.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/phymongshe_official", phone: "" },
  { code: "PLA5599", brand: "플래니스트 (PLANIST)", segment: "skincare", gubun: "스킨케어", email: "envy4101@dooricare.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/planist.official", phone: "" },
  { code: "PLU5469", brand: "플루", segment: "skincare", gubun: "헤어바디", email: "dwkang@plu.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/plu_official", phone: "" },
  { code: "POI5040", brand: "포인트투파이브세컨드", segment: "skincare", gubun: "향수", email: "025s@pointtwofivesecond.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/025s.official", phone: "" },
  { code: "POW5970", brand: "파워풀엑스", segment: "skincare", gubun: "헤어바디", email: "online@powerfulx.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/powerfulx.official", phone: "" },
  { code: "PRE7977", brand: "프리티스킨", segment: "skincare", gubun: "스킨케어", email: "prettyskin@prettyskin.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/prettyskinkorea", phone: "" },
  { code: "PRU7231", brand: "푸름웰니스", segment: "skincare", gubun: "스킨케어", email: "mkt@innovinekorea.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/prumwellness.official", phone: "" },
  { code: "PUR4408", brand: "PURITO", segment: "skincare", gubun: "스킨케어", email: "heynaturekr@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/purito_official", phone: "" },
  { code: "PYU4673", brand: "편강율", segment: "skincare", gubun: "헤어바디", email: "pyunkangyul_sales_kr@grunamu.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/pyunkangyul", phone: "" },
  { code: "RBO8990", brand: "알보우 (RboW)", segment: "skincare", gubun: "향수", email: "rbow@rbowofficial.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/rbow_official", phone: "" },
  { code: "RET8598", brand: "리터니티", segment: "skincare", gubun: "스킨케어", email: "returnity@returnity.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/returnity_official", phone: "" },
  { code: "REV4725", brand: "리브엠 (REVE:AM)", segment: "skincare", gubun: "스킨케어", email: "reveam@brive.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/reve_am_official", phone: "" },
  { code: "RIA5373", brand: "라이아 (RIAH)", segment: "skincare", gubun: "헤어바디", email: "sales@benow.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/riah.kr", phone: "" },
  { code: "RIC4790", brand: "리체나", segment: "skincare", gubun: "헤어바디", email: "sewha@sewha.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/richenna_official", phone: "" },
  { code: "RIR2756", brand: "리르", segment: "skincare", gubun: "스킨케어", email: "help@rire.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/rirecosmetic_official", phone: "" },
  { code: "ROM2349", brand: "롬앤", segment: "beauty", gubun: "색조", email: "romandyou@romand.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/romandyou", phone: "" },
  { code: "ROS9723", brand: "로제", segment: "skincare", gubun: "스킨케어", email: "roseeb2017@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/rosee_cosmetic", phone: "" },
  { code: "SAE3797", brand: "새로핸즈", segment: "skincare", gubun: "헤어바디", email: "saero@saero.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/saerohands", phone: "" },
  { code: "SAM2322", brand: "쌔뮤", segment: "skincare", gubun: "스킨케어", email: "sales@samchic.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/sam_u_official", phone: "" },
  { code: "SEE4594", brand: "시드랩 (Seedlab)", segment: "skincare", gubun: "이너뷰티", email: "hello@bepurposed.xyz", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/seedlab.official", phone: "" },
  { code: "SEE5879", brand: "씨들렛", segment: "skincare", gubun: "스킨케어", email: "seedletmake@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/seedlet.official", phone: "" },
  { code: "SEO5333", brand: "아임서울 더마 코스메틱 (I'M SEOUL)", segment: "skincare", gubun: "스킨케어", email: "she_said@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/imseoul_cosmetics", phone: "" },
  { code: "SHA1426", brand: "샹프리", segment: "skincare", gubun: "스킨케어", email: "cs@shangpree.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/shangpree.official", phone: "" },
  { code: "SHA6953", brand: "샤이샤이샤이", segment: "skincare", gubun: "스킨케어", email: "mkt3@shaishaishai.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/shaishaishai.official", phone: "" },
  { code: "SHA9957", brand: "샤이샤이샤이 (shaishaishai)", segment: "skincare", gubun: "스킨케어", email: "info@shaishaishai.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/shaishaishai.official", phone: "" },
  { code: "SID8799", brand: "시드물", segment: "skincare", gubun: "스킨케어", email: "help@sidmool.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/sidmool", phone: "" },
  { code: "SIM8216", brand: "씨 (Si)", segment: "skincare", gubun: "스킨케어", email: "miso@simkointernational.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/si_vegancosmetic", phone: "" },
  { code: "SKI1628", brand: "스킨랩", segment: "skincare", gubun: "스킨케어", email: "skinnlab@skinnlab.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "SKI2508", brand: "스킨덤", segment: "skincare", gubun: "스킨케어", email: "skindom3@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/skindom_usa", phone: "" },
  { code: "SKI2727", brand: "스킨메드", segment: "skincare", gubun: "스킨케어", email: "skinmedmk@daum.net", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/cutem_official", phone: "" },
  { code: "SKI3409", brand: "스킨79", segment: "beauty", gubun: "색조", email: "sk79beautymate@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/skin79_official", phone: "" },
  { code: "SKI7372", brand: "스킨나인", segment: "skincare", gubun: "스킨케어", email: "skinine@skinine.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/skininecosmetic_official", phone: "" },
  { code: "SKI7781", brand: "스킨큐어", segment: "skincare", gubun: "스킨케어", email: "cs@skincure.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/skincure_official", phone: "" },
  { code: "SLO9847", brand: "슬로우글로우 (SLOWGLOW)", segment: "skincare", gubun: "이너뷰티", email: "slowglow@gray-go.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/slowglow.kr", phone: "" },
  { code: "SNP4436", brand: "SNP", segment: "skincare", gubun: "스킨케어", email: "mkting@sdbiotech.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/snpbeauty", phone: "" },
  { code: "SOH1440", brand: "소미 (sohme)", segment: "beauty", gubun: "색조", email: "katie@sohmeskin.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/sohme.skin", phone: "" },
  { code: "SOM4656", brand: "썸바이미", segment: "skincare", gubun: "스킨케어", email: "global@somebymi.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/somebymi", phone: "" },
  { code: "SOO3841", brand: "수 (SOOO)", segment: "skincare", gubun: "헤어바디", email: "cs@makemake.it", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/sooo.kr_", phone: "" },
  { code: "SOO9072", brand: "순녹", segment: "skincare", gubun: "스킨케어", email: "peace@soonnoc.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/soonnoc__official", phone: "" },
  { code: "TAL7711", brand: "탈리다쿰 (Talitha Koum)", segment: "skincare", gubun: "스킨케어", email: "cs@talithakoum.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/talithakoum_official", phone: "" },
  { code: "TAM2177", brand: "탐뷰티 (TAM BEAUTY)", segment: "beauty", gubun: "색조", email: "tambeautofficial@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/tambeautyme", phone: "" },
  { code: "TAM3668", brand: "탐뷰티", segment: "beauty", gubun: "색조", email: "tambeautyofficial@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/tambeautyme", phone: "" },
  { code: "TFI3755", brand: "티핏", segment: "beauty", gubun: "색조", email: "ad@tfit.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/tfit.korea", phone: "" },
  { code: "THE1284", brand: "테라비코스", segment: "skincare", gubun: "스킨케어", email: "hpncmall@hpnc.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/thelavicos_korea", phone: "" },
  { code: "THE1947", brand: "메디큐브", segment: "skincare", gubun: "스킨케어", email: "cs123@apr-in.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/medicube_korea", phone: "" },
  { code: "THE2416", brand: "보스티나", segment: "skincare", gubun: "헤어바디", email: "af100@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "THE3221", brand: "더셀랩 (The Cell Lab)", segment: "skincare", gubun: "스킨케어", email: "thecell_cos@thecellcorp.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/thecell_lab", phone: "" },
  { code: "THE3371", brand: "더모멘트", segment: "skincare", gubun: "스킨케어", email: "themoment@themomentgroup.co.kr", contactEmail: "", contactName: "", instagram: "@themoment_official", phone: "" },
  { code: "THE6764", brand: "메디온", segment: "skincare", gubun: "스킨케어", email: "biz@medion.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/medion_official", phone: "" },
  { code: "THE8084", brand: "일론", segment: "skincare", gubun: "스킨케어", email: "office@illon.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/theillon_korea", phone: "" },
  { code: "TIA9935", brand: "티암", segment: "skincare", gubun: "스킨케어", email: "ad@tiam.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/tiam_korea", phone: "" },
  { code: "TOD2522", brand: "투데이이즈 (TODAY(IS))", segment: "skincare", gubun: "향수", email: "hello@todayis.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/todayis_official", phone: "" },
  { code: "TON2295", brand: "토니모리", segment: "skincare", gubun: "스킨케어", email: "hjyoon2104@tonymoly.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/tonymoly", phone: "" },
  { code: "TOU3841", brand: "톤28", segment: "skincare", gubun: "스킨케어", email: "ask@toun28.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/toun28_official", phone: "" },
  { code: "TOV3275", brand: "투비건 (Tovegan)", segment: "skincare", gubun: "스킨케어", email: "tov@tovstyle.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/tovegan.kr", phone: "" },
  { code: "TRO5128", brand: "트로이아루케", segment: "skincare", gubun: "스킨케어", email: "sisology.official@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/troiareuke_official", phone: "" },
  { code: "TST1251", brand: "TS샴푸", segment: "skincare", gubun: "헤어바디", email: "sales@talmo.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/ts_trillion", phone: "" },
  { code: "UNI3685", brand: "유니앤코어", segment: "skincare", gubun: "스킨케어", email: "unincore@unincore.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/unincore.official", phone: "" },
  { code: "UNL2962", brand: "언리시아", segment: "beauty", gubun: "색조", email: "sales@unleashiacosmetics.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/unleashia", phone: "" },
  { code: "UNV7998", brand: "언베니쉬", segment: "skincare", gubun: "향수", email: "official@unvanish.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/unvanish.official", phone: "" },
  { code: "VAL4735", brand: "발몬", segment: "skincare", gubun: "헤어바디", email: "grace@evasbiz.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/valmona_official", phone: "" },
  { code: "VEG5615", brand: "비그린 (Vegreen)", segment: "skincare", gubun: "스킨케어", email: "hello@vegreen.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/vegreen_official", phone: "" },
  { code: "VEG9683", brand: "비건제이", segment: "skincare", gubun: "스킨케어", email: "veganj@veganj.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/veganj.official", phone: "" },
  { code: "VEM8164", brand: "베몽테스", segment: "skincare", gubun: "스킨케어", email: "vemontes1@gmail.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/vemontes_official", phone: "" },
  { code: "VIE5265", brand: "비가노", segment: "skincare", gubun: "스킨케어", email: "viegano@naver.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/viegano_official", phone: "" },
  { code: "VIP1883", brand: "VIP코스메틱", segment: "beauty", gubun: "색조", email: "ohjehyuk@naver.com", contactEmail: "", contactName: "", instagram: "", phone: "" },
  { code: "VSN7009", brand: "닥터지", segment: "skincare", gubun: "스킨케어", email: "gmteam@gwss.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/dr.g_official", phone: "" },
  { code: "WAK8734", brand: "와칸", segment: "skincare", gubun: "헤어바디", email: "business@soky.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/wakan.official", phone: "" },
  { code: "WBM4928", brand: "웰빙헬스팜 고운발", segment: "skincare", gubun: "헤어바디", email: "whb0705@whp.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/3wb_wellbeing", phone: "" },
  { code: "WEL7798", brand: "웰킨", segment: "skincare", gubun: "헤어바디", email: "Kbeauty@kobizstar.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/wellkin_", phone: "" },
  { code: "WHA2618", brand: "화미사", segment: "skincare", gubun: "스킨케어", email: "cs@ensbeauty.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/whamisa.official", phone: "" },
  { code: "WHI9766", brand: "휩드 (Whipped)", segment: "skincare", gubun: "스킨케어", email: "business@whipped.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/whipped._official", phone: "" },
  { code: "WIS5449", brand: "나인위시스", segment: "skincare", gubun: "스킨케어", email: "help@9wishes.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/9wishes_official", phone: "" },
  { code: "WIZ8127", brand: "위즈메디", segment: "skincare", gubun: "스킨케어", email: "info@wizmedi.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/wizmedi_official", phone: "" },
  { code: "WNB3301", brand: "SW19", segment: "skincare", gubun: "향수", email: "support@sw19official.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/sw19_official", phone: "" },
  { code: "WON4205", brand: "원더바스", segment: "skincare", gubun: "헤어바디", email: "mccowork@csacosmic.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/wonderbath_official/reels/", phone: "" },
  { code: "WON9435", brand: "원진이펙트", segment: "skincare", gubun: "스킨케어", email: "beautyskin@beautyskincorp.co.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/wonjineffect_official", phone: "" },
  { code: "YOG2962", brand: "요거트네일", segment: "beauty", gubun: "색조", email: "willucorp@willucorp.kr", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/yogurtnail.co.kr", phone: "" },
  { code: "ZER2116", brand: "제로시피", segment: "skincare", gubun: "헤어바디", email: "km7177@kmkmp.com", contactEmail: "", contactName: "", instagram: "https://www.instagram.com/zerocipe_official", phone: "" },
];
